force-app/main/default/objects/Financial_Account__c/Financial_Account__c.object-meta.xml
<CustomObject>
    <description>To store the financial account details of Loan and Insurance</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Account__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>Financial_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Loan Amount Applied</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/EMI_Amount__c.field-meta.xml
<CustomField>
    <fullName>EMI_Amount__c</fullName>
    <label>EMI Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/First_EMI_Date__c.field-meta.xml
<CustomField>
    <fullName>First_EMI_Date__c</fullName>
    <label>First EMI Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>Financial_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Entity__c/Financial_Entity__c.object-meta.xml
<CustomObject>
    <label>Financial Entity</label>
    <nameField>
        <label>Financial Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Entities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Entity__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Entities</relationshipLabel>
    <relationshipName>Financial_Entities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Entity__c/fields/Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Financial_Account__c</fullName>
    <label>Financial Account</label>
    <referenceTo>Financial_Account__c</referenceTo>
    <relationshipLabel>Financial Entities</relationshipLabel>
    <relationshipName>Financial_Entities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Financial_Entity_AC_Detail__c/Financial_Entity_AC_Detail__c.object-meta.xml
<CustomObject>
    <label>Financial Entity AC Detail</label>
    <nameField>
        <label>Financial Entity AC Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Entity AC Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Entity_AC_Detail__c/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Financial_Entity_AC_Detail__c/fields/Bank_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Type__c</fullName>
    <label>Bank Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Savings</fullName>
            </value>
            <value>
                <fullName>Current</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Financial_Entity_AC_Detail__c/fields/Banking_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Banking_Account_Name__c</fullName>
    <label>Banking Account Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Financial_Entity_AC_Detail__c/fields/Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Financial_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Account</label>
    <referenceTo>Financial_Account__c</referenceTo>
    <relationshipLabel>Financial Entity AC Details</relationshipLabel>
    <relationshipName>Financial_Entity_AC_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Entity_AC_Detail__c/fields/Financial_Entity__c.field-meta.xml
<CustomField>
    <fullName>Financial_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Entity</label>
    <referenceTo>Financial_Entity__c</referenceTo>
    <relationshipLabel>Financial Entity AC Details</relationshipLabel>
    <relationshipName>Financial_Entity_AC_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/API_PennyDropCalloutTest.cls
@isTest
public class API_PennyDropCalloutTest {

    // Utility method to simulate HTTP response
    private class MockHttpResponseGenerator implements HttpCalloutMock {
        private Integer statusCode;
        private String body;
        
        public MockHttpResponseGenerator(Integer statusCode, String body) {
            this.statusCode = statusCode;
            this.body = body;
        }
        
        public HTTPResponse respond(HTTPRequest request) {
            HttpResponse response = new HttpResponse();
            response.setStatusCode(statusCode);
            response.setBody(body);
            return response;
        }
    }
    
    
	@isTest
    public static void testApiUpdateStatus(){
        Account testAccount = TestUtility.createTestAccount();
        //insert testAccount;
        Opportunity testOpportunity = TestUtility.createTestOpportunity(testAccount.Id);
        insert testOpportunity;
        
        Financial_Account__c faAccount = new Financial_Account__c();
        faAccount.Account_Name__c = testAccount.Id;
        faAccount.Amount__c = 5000;
        faAccount.EMI_Amount__c = 300;
        faAccount.First_EMI_Date__c = system.today();
        faAccount.Opportunity__c = testOpportunity.Id;
        insert faAccount;
        Financial_Entity__c FinancialEntity = new Financial_Entity__c();
        
        FinancialEntity.Financial_Account__c =faAccount.Id;
        FinancialEntity.Account_Name__c = testAccount.Id;
        insert FinancialEntity;
        
        Financial_Entity_AC_Detail__c feac = new Financial_Entity_AC_Detail__c();
        feac.Bank_Account_Number__c = 'Test Bank Account';
        feac.Bank_Account_Type__c = 'Savings';
        feac.Bank_Name__c = 'Axis Bank';
        feac.Branch_Name__c = 'Kormanagala';
        feac.Banking_Account_Name__c = 'Test Banking Name';
        feac.Financial_Account__c = faAccount.Id;
        feac.Financial_Entity__c = FinancialEntity.Id;
        feac.IFSC_Code__c = 'test IFSC';
        insert  feac;
        
        Task taskRec= new Task();
        taskRec.WhatId = testOpportunity.Id;
        taskRec.Attribute1__c = feac.Id;
        insert taskRec;
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(200, '{"message": "success",  "status": "Verified"}'));
        
        
        API_PennyDropCallout.processResponseData(taskRec.Id);
        Test.stopTest();
    }
}