force-app/main/default/objects/Account/fields/Originating_System_URL_ID__c.field-meta.xml
<CustomField>
    <fullName>Originating_System_URL_ID__c</fullName>
    <label>Originating System URL ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Handler__c/Document_Handler__c.object-meta.xml
<CustomObject>
    <label>Document Handler</label>
    <nameField>
        <label>Document Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Handler</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Handler__c/fields/Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Financial_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Account</label>
    <referenceTo>Financial_Account__c</referenceTo>
    <relationshipLabel>Document Handler</relationshipLabel>
    <relationshipName>Document_Handler</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Handler__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Document Handler</relationshipLabel>
    <relationshipName>Document_Handler</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/Financial_Account__c.object-meta.xml
<CustomObject>
    <description>To store the financial account details of Loan and Insurance</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Account__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>Financial_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Loan Amount Applied</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/Amount_Available_For_Disbursement__c.field-meta.xml
<CustomField>
    <fullName>Amount_Available_For_Disbursement__c</fullName>
    <formula>Sanctioned_Amount__c -  Receivables_Amount__c -  Payable_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount Available For Disbursement</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/Amount_Created__c.field-meta.xml
<CustomField>
    <fullName>Amount_Created__c</fullName>
    <label>Amount Created</label>
    <summarizedField>Paybale__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Paybale__c.Status__c</field>
        <operation>equals</operation>
        <value>Accepted By Bank</value>
    </summaryFilterItems>
    <summaryForeignKey>Paybale__c.Financial_Account__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/Amount_Yet_To_Be_Credited__c.field-meta.xml
<CustomField>
    <fullName>Amount_Yet_To_Be_Credited__c</fullName>
    <formula>Sanctioned_Amount__c - Receivables_Amount__c - Amount_Created__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount Yet To Be Credited</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/Borrower_Name__c.field-meta.xml
<CustomField>
    <fullName>Borrower_Name__c</fullName>
    <formula>Account_Name__r.Name</formula>
    <label>Borrower Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/EMI_Amount__c.field-meta.xml
<CustomField>
    <fullName>EMI_Amount__c</fullName>
    <label>EMI Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <description>Data Origination/Source unique record identifying id</description>
    <externalId>true</externalId>
    <label>Data Originating External ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/First_EMI_Date__c.field-meta.xml
<CustomField>
    <fullName>First_EMI_Date__c</fullName>
    <label>First EMI Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/LMS_Application_ID__c.field-meta.xml
<CustomField>
    <fullName>LMS_Application_ID__c</fullName>
    <label>LMS Application ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/LMS_System_Name__c.field-meta.xml
<CustomField>
    <fullName>LMS_System_Name__c</fullName>
    <description>contains the Name of the System where the the LMS data exists</description>
    <label>LMS System Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Originating_System</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/LMS_URL_ID__c.field-meta.xml
<CustomField>
    <fullName>LMS_URL_ID__c</fullName>
    <label>LMS URL ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/Loan_Category__c.field-meta.xml
<CustomField>
    <fullName>Loan_Category__c</fullName>
    <description>Loan Categoty / Loan Type</description>
    <label>Loan Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Loan_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/Loan_Closure_Required__c.field-meta.xml
<CustomField>
    <fullName>Loan_Closure_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Boolean to check if the previous loan of the applicants are required to be closed</description>
    <label>Loan Closure Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/LOS_Application_ID__c.field-meta.xml
<CustomField>
    <fullName>LOS_Application_ID__c</fullName>
    <label>LOS Application ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/LOS_System_Name__c.field-meta.xml
<CustomField>
    <fullName>LOS_System_Name__c</fullName>
    <label>LOS System Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Originating_System</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/LOS_URL_ID__c.field-meta.xml
<CustomField>
    <fullName>LOS_URL_ID__c</fullName>
    <label>LOS URL ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>Financial_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/Originating_Branch__c.field-meta.xml
<CustomField>
    <fullName>Originating_Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Originating Branch</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Accounts (Originating Branch)</relationshipLabel>
    <relationshipName>Financial_Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Entity__c/Financial_Entity__c.object-meta.xml
<CustomObject>
    <label>Financial Entity</label>
    <nameField>
        <label>Financial Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Entities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Entity__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Entities</relationshipLabel>
    <relationshipName>Financial_Entities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Entity__c/fields/Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Financial_Account__c</fullName>
    <label>Financial Account</label>
    <referenceTo>Financial_Account__c</referenceTo>
    <relationshipLabel>Financial Entities</relationshipLabel>
    <relationshipName>Financial_Entities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Financial_Entity_AC_Detail__c/Financial_Entity_AC_Detail__c.object-meta.xml
<CustomObject>
    <label>Financial Entity AC Detail</label>
    <nameField>
        <label>Financial Entity AC Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Entity AC Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Entity_AC_Detail__c/fields/Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Financial_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Account</label>
    <referenceTo>Financial_Account__c</referenceTo>
    <relationshipLabel>Financial Entity AC Details</relationshipLabel>
    <relationshipName>Financial_Entity_AC_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MODT_Details__c/MODT_Details__c.object-meta.xml
<CustomObject>
    <label>MODT Details</label>
    <nameField>
        <displayFormat>MODT-{00000000}</displayFormat>
        <label>MODT Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MODT Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MODT_Details__c/fields/Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Financial_Account__c</fullName>
    <label>Financial Account</label>
    <referenceTo>Financial_Account__c</referenceTo>
    <relationshipLabel>MODT Details</relationshipLabel>
    <relationshipName>MODT_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Paybale__c/Paybale__c.object-meta.xml
<CustomObject>
    <label>Payable</label>
    <nameField>
        <label>Paybales Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Paybales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Paybale__c/fields/Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Financial_Account__c</fullName>
    <label>Financial Account</label>
    <referenceTo>Financial_Account__c</referenceTo>
    <relationshipName>Paybales</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Paybale__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Paybales</relationshipLabel>
    <relationshipName>Paybales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PayableDetailsControllerTest.cls
@isTest
private class PayableDetailsControllerTest {

    @testSetup
    static void setup() {
        // Initialize test data using TestUtility class
        TestUtility.APICallingSystemDetails();
    }

    @isTest
    static void testGetAllFinancialEntityWithDetails() {
        Test.startTest();
        Financial_Account__c testFA = TestUtility.CreateFinancialAccountInstance();
        PayableDetailsController.getAllFinancialEntityWithDetails(testFA.Id);
        Test.stopTest();
    }

    @isTest
    static void testGetAllFinancialEntityWithDetailsModt() {
        Test.startTest();
        Financial_Account__c testFA = TestUtility.CreateFinancialAccountInstance();
        PayableDetailsController.getAllFinancialEntityWithDetailsModt(testFA.Id);
        Test.stopTest();
    }

    @isTest
    static void testAllowedEntityForMemoCreation() {
        Test.startTest();
        Financial_Account__c testFA = TestUtility.CreateFinancialAccountInstance();
        system.debug('testFA ===> ' +testFA.Id);
        Financial_Account__c FATest = [SELECT Account_Name__c,Amount_Available_For_Disbursement__c,Amount_Created__c,
                                       Amount_Yet_To_Be_Credited__c,Amount__c,Borrower_Name__c,CreatedDate,EMI_Amount__c,
                                       External_ID__c,First_EMI_Date__c,Id,LMS_Application_ID__c,LMS_System_Name__c,
                                       LMS_URL_ID__c,Loan_Category__c,Loan_Closure_Required__c,LOS_Application_ID__c,
                                       LOS_System_Name__c,LOS_URL_ID__c,Name,Opportunity__c,Originating_Branch__c,
                                       Originating_System_URL_ID__c,Originating_System__c,OwnerId,Payable_Amount__c,
                                       RecordTypeId,
                                       Sanctioned_Amount__c,Sanction_Date__c,SystemModstamp,Tenuer__c 
                                       FROM Financial_Account__c where Id =: testFA.Id];
        List<Financial_Entity__c> FEList = new List<Financial_Entity__c>();
        Financial_Entity__c testFE = TestUtility.CreateFinancialEntityInstance();
        testFE.Financial_Account__c=testFA.id;
        testFE.Amount_To_Be_Disbursed__c = 5876787;
        testFE.Entity_Type__c = 'Financial Institute (BT)';
        FEList.add(testFE);
        
        Financial_Entity__c testFE1 = TestUtility.CreateFinancialEntityInstance();
        testFE1.Financial_Account__c=testFA.id;
        testFE1.Entity_Type__c = 'Financial Institute (Debt)';
        testFE.Amount_To_Be_Disbursed__c = 587678776;
        FEList.add(testFE1);
        
        insert FEList;
        PayableDetailsController.AllowedEntityForMemoCreation(FATest.Id);
        Test.stopTest();
    }

    @isTest
    static void testUpsertPayableRecord() {
        Test.startTest();
        Paybale__c payable = TestUtility.createMODTInstance();
        List<Paybale__c> payablesList = new List<Paybale__c>{payable};
        PayableDetailsController.upsertPayableRecord(payablesList);
        Test.stopTest();
    }
    
    @isTest
    static void testgetAllFinancialEntityWithDetailsDups() {
        Test.startTest();
        Financial_Account__c FATest = TestUtility.CreateFinancialAccountInstance();
		        
        Financial_Entity__c FETest =  TestUtility.CreateFinancialEntityInstance();
        FETest.Financial_Account__c = FATest.Id;
        Insert FETest;
        
         Document_Metadata__c testDocumentMetaData1 = TestUtility.createDocumentmetadata();
        testDocumentMetaData1.Related_To_sObject__c = 'Financial_Entity_AC_Detail__c';
        Insert testDocumentMetaData1;
        
        Process_Attribute_Dcoument_Detail__c PADD= TestUtility.ProcessAttributeDocumentDetailInstance();
        PADD.Document_Metadata__c = testDocumentMetaData1.Id;
        //PADD.Related_To_sObject__c ='Financial_Entity_AC_Detail__c';
        insert PADD;
        
        
       
        
        Task testTask = TestUtility.CreateTaskInstance();
        testTask.Process_Path_Task_Detail__c = PADD.Process_Path_Task_Detail__c;
        insert testTask;
        
         Financial_Entity_AC_Detail__c FEACDetailsTest =  TestUtility.CreateFiancialEntityAcctDetailInsatance();
        FEACDetailsTest.Financial_Entity__c = FETest.Id;
        FEACDetailsTest.Task_ID__c = testTask.Id;
        insert FEACDetailsTest;
        
        
        PayableDetailsController.getAllFinancialEntityWithDetailsDups(FATest.Id);
        Test.stopTest();
    }

    @isTest
    static void testDeletePayableRecord() {
        Test.startTest();
        Paybale__c payable = TestUtility.createMODTInstance();
        PayableDetailsController.deletePayableRecord(payable.Id);
        Test.stopTest();
    }

    @isTest
    static void testGetRelatedContactAccount() {
        Test.startTest();
        Financial_Account__c testFA = TestUtility.CreateFinancialAccountInstance();
        PayableDetailsController.getRelatedContactAccount(testFA.Id);
        Test.stopTest();
    }

    @isTest
    static void testUpsertMODTRecords() {
        Test.startTest();
        
        Process_Attribute_Dcoument_Detail__c PADD = TestUtility.ProcessAttributeDocumentDetailInstance();
        //PADD.Related_To_sObject__c = 'MODT_Details__c';
        insert PADD;
         Task tas = TestUtility.CreateTaskInstance();
        tas.Process_Path_Task_Detail__c = PADD.Process_Path_Task_Detail__c;
        insert tas;
        
        
        MODT_Details__c modt = TestUtility.CreateMODTDetailInsatance();
        modt.Task_Id__c =tas.Id;
       
        insert modt;
        
        Document_handler__c DH = new Document_handler__c();
        DH.Document_Metadata__c = PADD.Document_Metadata__c;
        DH.Process_Attribute_Dcoument_Detail__c = PADD.ID;
        DH.Extended_SObject_RecordId__c = modt.Id;
        Insert DH;
        //PayableDetailsController.deleteMODTRecord(modt.Id);
        //Test.stopTest();
        List<MODT_Details__c> modtList = new List<MODT_Details__c>{modt};
            try {
                PayableDetailsController.upsertMODTRecords(modtList);
            } catch (Exception e) {
                // Log the exception or handle it if necessary.
            }
        Test.stopTest();
    }

    @isTest
    static void testDeleteMODTRecord() {
        Test.startTest();
        
        Process_Attribute_Dcoument_Detail__c PADD = TestUtility.ProcessAttributeDocumentDetailInstance();
        //PADD.Related_To_sObject__c = 'MODT_Details__c';
        insert PADD;
         Task tas = TestUtility.CreateTaskInstance();
        tas.Process_Path_Task_Detail__c = PADD.Process_Path_Task_Detail__c;
        insert tas;
        
        
        MODT_Details__c modt = TestUtility.CreateMODTDetailInsatance();
        modt.Task_Id__c =tas.Id;
       
        insert modt;
        
        Document_handler__c DH = new Document_handler__c();
        DH.Document_Metadata__c = PADD.Document_Metadata__c;
        DH.Process_Attribute_Dcoument_Detail__c = PADD.ID;
        DH.Extended_SObject_RecordId__c = modt.Id;
        Insert DH;
        PayableDetailsController.deleteMODTRecord(modt.Id);
        Test.stopTest();
    }

    @isTest
    static void testUpdateMODT() {
        
        Test.startTest();
        
        Process_Attribute_Dcoument_Detail__c PADD = TestUtility.ProcessAttributeDocumentDetailInstance();
        //PADD.Related_To_sObject__c = 'MODT_Details__c';
        insert PADD;
        
        
        
        
         Task tas = TestUtility.CreateTaskInstance();
        tas.Process_Path_Task_Detail__c = PADD.Process_Path_Task_Detail__c;
        insert tas;
        
        
        MODT_Details__c modt = TestUtility.CreateMODTDetailInsatance();
        modt.Task_Id__c =tas.Id;
       
        insert modt;
        
        Document_handler__c DH = new Document_handler__c();
        DH.Document_Metadata__c = PADD.Document_Metadata__c;
        DH.Process_Attribute_Dcoument_Detail__c = PADD.ID;
        DH.Extended_SObject_RecordId__c = modt.Id;
        Insert DH;
        PayableDetailsController.updateMODT(modt.Id, true, 'MODT Created');
        Test.stopTest();
        /*Test.startTest();
        MODT_Details__c modt = TestUtility.CreateMODTDetailInsatance();
        insert modt;
        PayableDetailsController.updateMODT(modt.Id, true, 'Closed');
        Test.stopTest();*/
    }

    @isTest
    static void testFetchDataFromWire() {
        Test.startTest();
        Financial_Account__c testFA = TestUtility.CreateFinancialAccountInstance();
        PayableDetailsController.fetchDataFromWire(testFA.Id);
        Test.stopTest();
    }

    @isTest
    static void testVerifyExistingRecord() {
        Test.startTest();
        Account account = TestUtility.createTestAccount();
        PayableDetailsController.verifyExistingRecord(account.Email_Id__c);
        Test.stopTest();
    }

    @isTest
    static void testUppesertSobject() {
        Test.startTest();
        List<Financial_Entity_AC_Detail__c> acDetails = new List<Financial_Entity_AC_Detail__c>{TestUtility.CreateFiancialEntityAcctDetailInsatance()};
        PayableDetailsController.uppesertSobject(acDetails);
        Test.stopTest();
    }

    @isTest
    static void testCreateTask() {
        Test.startTest();
         Process_Task_Detail__c mockProcessTaskDetail = new Process_Task_Detail__c(Subject__c = 'Communication - Email');
        insert mockProcessTaskDetail;
        
         Process_Path__c  testPP=TestUtility.createTestProcessPath();
      //  Process_Task_Detail__c processTaskDetail = createMockProcessTaskDetail();
        Process_Path_Task_Detail__c testPPTD = new Process_Path_Task_Detail__c();
        testPPTD.isActive__c=true;
        testPPTD.Subject__c = 'Test Subject';
        testPPTD.Manual_API_Call_Out__c = true;
        testPPTD.Business_Step_No__c = 45;
        testPPTD.Task_Owner_Name__c = 'Test Owner';
        testPPTD.Process_Path__c=testPP.id;
        testPPTD.Process_Task_Detail__c = mockProcessTaskDetail.Id;
        testPPTD.Execution_Serial_No__c = '1';
        testPPTD.Task_Owner_Type__c = 'System';
        insert testPPTD;
        //insert mockProcessTaskDetail;
        
        Task parentTask = TestUtility.CreateTaskInstance();
        insert parentTask;
        PayableDetailsController.createTask('Communication - Email', parentTask.Id, parentTask.Id);
        Test.stopTest();
    }
    
    @isTest
    static void testGetDependentPicklistValues() {
        Test.startTest();
        // Using Account and Industry field as an example; adjust based on your org's schema
        //Map<Object, List<String>> result = PayableDetailsController.getDependentPicklistValues('Process_Attribute__c', 'Case_Sub_Category__c');
        Test.stopTest();
        // Normally, you would use System.assert methods to validate the result, 
        // but since you prefer not to use assertions, we'll just ensure the method executes.
    }
    
    @isTest
    Public static void TestcreateAccount(){
        
         Test.startTest();
        // Using Account and Industry field as an example; adjust based on your org's schema
        //Map<Object, List<String>> result = PayableDetailsController.getDependentPicklistValues('Account', 'Industry');
        PayableDetailsController.createAccount('Test Name','testing@mail.com','9876543210');
        Test.stopTest();
    }
    
    @isTest
    static void testCreateAccountContactDetailsOnBehalfOfPayeeNumber() {
        Test.startTest();
        // Prepare the wrapper list
        List<PayableDetailsController.AccountCOntactPayeewrapper> wrapperList = new List<PayableDetailsController.AccountCOntactPayeewrapper>();
        PayableDetailsController.AccountCOntactPayeewrapper wrapper = new PayableDetailsController.AccountCOntactPayeewrapper();
        wrapper.payeeEmail = 'test@example.com';
        wrapper.payeePhone = '1234567890';
        wrapper.index = 1;
        wrapper.name = 'Test Account';
        
		List<Financial_Entity__c> FEList = new List<Financial_Entity__c>();
        // Assume this method sets up a related Financial_Entity__c record
        Account acc = TestUtility.createTestAccount();
        
        Contact con = TestUtility.CreateContactINstance();
        con.AccountId = acc.Id;
        Insert con;
        Financial_Entity__c FinancialEntityTest = TestUtility.CreateFinancialEntityInstance();
        FinancialEntityTest.Account_Name__c = acc.Id;
        FEList.add(FinancialEntityTest);
        //insert FinancialEntityTest;
        
        Financial_Entity__c FinancialEntityTest1 = TestUtility.CreateFinancialEntityInstance();
        FEList.add(FinancialEntityTest1);
        
        Insert FEList;
        wrapper.relatedFinancialEntity = FEList[0];
        wrapperList.add(wrapper);
        
        PayableDetailsController.createAccountContactDetailsOnBehalofPayeeNumber(wrapperList);
        Test.stopTest();
        // No assertions are included as per your request
    }



    // Add more test methods as needed to cover all methods in PayableDetailsController
}