force-app/main/default/objects/Account/fields/Product_Bussiness_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Bussiness_Line__c</fullName>
    <defaultValue>&apos;Not Assigned&apos;</defaultValue>
    <description>To populate the value of business Line from which the account was created</description>
    <label>Product Bussiness Line</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DO</fullName>
            </value>
            <value>
                <fullName>NU Score</fullName>
            </value>
            <value>
                <fullName>Nimbus</fullName>
            </value>
            <value>
                <fullName>SCF</fullName>
            </value>
            <value>
                <fullName>CLM</fullName>
            </value>
            <value>
                <fullName>EL</fullName>
            </value>
            <value>
                <fullName>LAP</fullName>
            </value>
            <value>
                <fullName>Shipping</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Financial_Account__c/Financial_Account__c.object-meta.xml
<CustomObject>
    <description>To store the financial account details of Loan and Insurance</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Account__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>Financial_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/Borrower_Name__c.field-meta.xml
<CustomField>
    <fullName>Borrower_Name__c</fullName>
    <formula>Account_Name__r.Name</formula>
    <label>Borrower Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>Financial_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Process_Attribute_Review_Detail__c/Process_Attribute_Review_Detail__c.object-meta.xml
<CustomObject>
    <label>Process Attribute Review Detail</label>
    <nameField>
        <label>Process Attribute Review Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Attribute Review Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Process_Attribute_Review_Detail__c/fields/Process_Attribute_Review_Detail__c.field-meta.xml
<CustomField>
    <fullName>Process_Attribute_Review_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Process Attribute Review Detail</label>
    <referenceTo>Process_Attribute_Review_Detail__c</referenceTo>
    <relationshipLabel>Process Attribute Review Details</relationshipLabel>
    <relationshipName>Process_Attribute_Review_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Process_Attribute_Review_Detail__c/fields/Process_Path__c.field-meta.xml
<CustomField>
    <fullName>Process_Path__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Process Path</label>
    <referenceTo>Process_Path__c</referenceTo>
    <relationshipLabel>Process Attribute Review Details</relationshipLabel>
    <relationshipName>Process_Attribute_Review_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Process_Attribute_Review_Detail__c/fields/Process_Path_Task_Detail__c.field-meta.xml
<CustomField>
    <fullName>Process_Path_Task_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Process Path Task Detail</label>
    <referenceTo>Process_Path_Task_Detail__c</referenceTo>
    <relationshipLabel>Process Attribute Review Details</relationshipLabel>
    <relationshipName>Process_Attribute_Review_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Process_Path__c/Process_Path__c.object-meta.xml
<CustomObject>
    <description>Junction Object to be used to refer Process Path Detail (PAD) for Process Attribute</description>
    <label>Process Path</label>
    <nameField>
        <label>Process Path ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Paths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Process_Path_Task_Detail__c/Process_Path_Task_Detail__c.object-meta.xml
<CustomObject>
    <label>Process Path Task Detail</label>
    <nameField>
        <label>Process Path Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Path Task Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Process_Path_Task_Detail__c/fields/Business_Step_No__c.field-meta.xml
<CustomField>
    <fullName>Business_Step_No__c</fullName>
    <label>Business Step No</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Process_Path_Task_Detail__c/fields/Execution_Serial_No__c.field-meta.xml
<CustomField>
    <fullName>Execution_Serial_No__c</fullName>
    <label>Execution Serial No</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SL_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Process_Path_Task_Detail__c/fields/Process_Path__c.field-meta.xml
<CustomField>
    <fullName>Process_Path__c</fullName>
    <label>Process Path</label>
    <referenceTo>Process_Path__c</referenceTo>
    <relationshipLabel>Process Path Task Details</relationshipLabel>
    <relationshipName>Process_Path_Task_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Process_Path_Task_Detail__c/fields/Process_Task_Detail__c.field-meta.xml
<CustomField>
    <fullName>Process_Task_Detail__c</fullName>
    <label>Process Task Detail</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Process_Task_Detail__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Process_Task_Detail__c</referenceTo>
    <relationshipLabel>Process Path Task Details</relationshipLabel>
    <relationshipName>Process_Path_Task_Details</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Process_Path_Task_Detail__c/fields/Task_Owner_Name__c.field-meta.xml
<CustomField>
    <fullName>Task_Owner_Name__c</fullName>
    <label>Task Owner Name</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Process_Path_Task_Detail__c/fields/Task_Owner_Type__c.field-meta.xml
<CustomField>
    <fullName>Task_Owner_Type__c</fullName>
    <label>Task Owner Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Task_Owner_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Process_Review_Checklist_FACT__c/Process_Review_Checklist_FACT__c.object-meta.xml
<CustomObject>
    <label>Process Review Checklist FACT</label>
    <nameField>
        <displayFormat>PRCF-{0000}</displayFormat>
        <label>Process Review Checklist FACT</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process Review Checklist FACTs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Process_Review_Checklist_FACT__c/fields/Parent_Task_Id__c.field-meta.xml
<CustomField>
    <fullName>Parent_Task_Id__c</fullName>
    <label>Parent Task Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Process_Review_Checklist_FACT__c/fields/Process_Attribute_Review_Detail__c.field-meta.xml
<CustomField>
    <fullName>Process_Attribute_Review_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created This Field to Store the ThreadId Of Reviewer</description>
    <label>Process Attribute Review Detail</label>
    <referenceTo>Process_Attribute_Review_Detail__c</referenceTo>
    <relationshipLabel>Process Review Checklist FACTs</relationshipLabel>
    <relationshipName>Process_Review_Checklist_FACTs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Process_Review_Checklist_FACT__c/fields/Process_Path_Task_Detail__c.field-meta.xml
<CustomField>
    <fullName>Process_Path_Task_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Process Path Task Detail</label>
    <referenceTo>Process_Path_Task_Detail__c</referenceTo>
    <relationshipLabel>Process Review Checklist FACTs</relationshipLabel>
    <relationshipName>Process_Review_Checklist_FACTs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Process_Task_Detail__c/Process_Task_Detail__c.object-meta.xml
<CustomObject>
    <label>Process Task Detail</label>
    <nameField>
        <label>Process Task Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Task Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Child_components_ControllerTest.cls
@isTest
private class Child_components_ControllerTest {
    
    @isTest
    static void testWrapperClassReviewerDetailFromApex() {
        Process_Task_Detail__c testPTD =TestUtility.createMockProcessTaskDetail();
        //insert testPTD;
        Process_Path__c  testPP=TestUtility.createTestProcessPath();
       	//insert testPP;
        Process_Path_Task_Detail__c  testPPTD=TestUtility.createPPTD();
        testPPTD.Process_Path__c=testPP.id;
        testPPTD.Business_Step_No__c=3;
        testPPTD.Execution_Serial_No__c='4';
        testPPTD.Task_Owner_Type__c='System';
        testPPTD.Task_Owner_Name__c='Test Task Owner';
        testPPTD.Process_Task_Detail__c=testPTD.id;
        insert testPPTD;	
        
        Process_Attribute_Review_Detail__c PARD = TestUtility.createPARDInstance();
        PARD.Process_Path__c = testPP.Id;
        PARD.Process_Path_Task_Detail__c = testPPTD.Id;
        insert PARD;
        
        Process_Attribute_Review_Detail__c PARD2 = TestUtility.createPARDInstance();
        PARD2.Process_Path__c = testPP.Id;
        PARD2.Process_Path_Task_Detail__c = testPPTD.Id;
        insert PARD2;
        
        Account TestAccount =TestUtility.createaccountInstance();
        TestAccount.Product_Bussiness_Line__c='NU Score';
        insert TestAccount ;
        task testTask=TestUtility.CreateTaskInstance();
        testTask.WhatId=TestAccount.id;
        testTask.Process_Path_Task_Detail__c=testPPTD.id;
        insert testTask;
        
        // Call the method to test
        Child_components_Controller.WrapperClassReviewer result = Child_components_Controller.WrapperClassReviewerDetailFromApex(testTask.Id);
        
        // Perform assertions
        System.assertNotEquals(null, result, 'Expected a non-null result');
        // Add more assertions based on the expected behavior of the method
    }
    
    @isTest
    static void testReturnWrapper() {
        // Create test data
        // 
         String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        // This code runs as the system user
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
         User u = new User(Alias = 'standt', Email='standarduser@testorg.com',
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
        LocaleSidKey='en_US', ProfileId = p.Id,
        TimeZoneSidKey='America/Los_Angeles',
         UserName='standarduser2@devtestorg.com');
        insert u;
        
        
        Process_Path__c  testPP= new Process_Path__c();
        testPP.Name='1234';
        testPP.isActive__c=true;
        insert testPP;
        String WhatId;
        Process_Path_Task_Detail__c testPPTD = new Process_Path_Task_Detail__c();
        testPPTD.isActive__c=true;
        testPPTD.Process_Path__c=testPP.id;
        
        Account TestAccount =TestUtility.createaccountInstance();
        TestAccount.Product_Bussiness_Line__c='NU Score';
        insert TestAccount ;
        task testTask=TestUtility.CreateTaskInstance();
        testTask.WhatId=TestAccount.id;
        testTask.Process_Path_Task_Detail__c=testPPTD.id;
        testTask.OwnerId = u.Id;
        insert testTask; 
        
        // Call the method to test
       
        system.runAs(u){
            Child_components_Controller.wrapperClass result = Child_components_Controller.returnWrapper(testTask.Id);
            System.assertNotEquals(null, result, 'Expected a non-null result');
        }
        
        
        // Perform assertions
        
        // Add more assertions based on the expected behavior of the method
    }
    
    @isTest
    static void testPassValueForApproval() {
        
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        // This code runs as the system user
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
         User u = new User(Alias = 'standt', Email='standarduser@testorg.com',
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
        LocaleSidKey='en_US', ProfileId = p.Id,
        TimeZoneSidKey='America/Los_Angeles',
         UserName='standarduser2@devtestorg.com');
        insert u;
        // Create test data
        Process_Path__c  testPP= new Process_Path__c();
        testPP.Name='1234';
        testPP.isActive__c=true;
        insert testPP;
        String WhatId;
        Process_Path_Task_Detail__c testPPTD = new Process_Path_Task_Detail__c();
        testPPTD.isActive__c=true;
        testPPTD.Process_Path__c=testPP.id;
        
        Account TestAccount =TestUtility.createaccountInstance();
        TestAccount.Product_Bussiness_Line__c='NU Score';
        insert TestAccount ;
        task testTask=TestUtility.CreateTaskInstance();
        testTask.WhatId=TestAccount.id;
        testTask.Process_Path_Task_Detail__c=testPPTD.id;
        testTask.ownerId = u.Id;
        insert testTask; 
        
        // Call the method to test
        Child_components_Controller.PassValueForApproval(testTask.Id,new List<Task>{testTask},'Reviewer1');
        
        // Perform assertions if needed
    }
    @isTest
    static void testCallCheckCurrentUserEditRight() {
        // Create test data
        Process_Path__c  testPP= new Process_Path__c();
        testPP.Name='1234';
        testPP.isActive__c=true;
        insert testPP;
        
        Process_Path_Task_Detail__c testPPTD = new Process_Path_Task_Detail__c();
        testPPTD.isActive__c=true;
        testPPTD.Process_Path__c=testPP.id;
        
        Account TestAccount =TestUtility.createaccountInstance();
        TestAccount.Product_Bussiness_Line__c='NU Score';
        insert TestAccount ;
        task testTask=TestUtility.CreateTaskInstance();
        testTask.WhatId=TestAccount.id;
        testTask.Process_Path_Task_Detail__c=testPPTD.id;
       // insert testTask; 
        
        
        // Call the method to test
        //boolean result = Child_components_Controller.CallCheckCurrentUserEditRight(taskRecord.Id);
        
        // Perform assertions
        //System.assertNotEquals(null, result, 'Expected a non-null result');
        // Add more assertions based on the expected behavior of the method
    }
    
    @isTest
    static void testUpdateTaskStatus() {
        // Create test data
        Process_Path__c  testPP= new Process_Path__c();
        testPP.Name='1234';
        testPP.isActive__c=true;
        insert testPP;
        
        Process_Path_Task_Detail__c testPPTD = new Process_Path_Task_Detail__c();
        testPPTD.isActive__c=true;
        testPPTD.Process_Path__c=testPP.id;
        Account TestAccount =TestUtility.createaccountInstance();
        TestAccount.Product_Bussiness_Line__c='NU Score';
        insert TestAccount ;
        task testTask=TestUtility.CreateTaskInstance();
        testTask.WhatId=TestAccount.id;
        testTask.Process_Path_Task_Detail__c=testPPTD.id;
       insert testTask;        
        
        
        // Call the method to test
        List<Task> result = Child_components_Controller.UpdateTaskStatus(null,'Approved', new List<Id>{testTask.Id});
        
        // Perform assertions
        System.assertNotEquals(null, result, 'Expected a non-null result');
        // Add more assertions based on the expected behavior of the method
    }
    
    @isTest
    static void testUpdateTasks() {
        // Create test data
        Process_Path__c  testPP= new Process_Path__c();
        testPP.Name='1234';
        testPP.isActive__c=true;
        insert testPP;
        String WhatId;
        Process_Path_Task_Detail__c testPPTD = new Process_Path_Task_Detail__c();
        testPPTD.isActive__c=true;
        testPPTD.Process_Path__c=testPP.id;
        
        Account TestAccount =TestUtility.createaccountInstance();
        TestAccount.Product_Bussiness_Line__c='NU Score';
        insert TestAccount ;
        task testTask=TestUtility.CreateTaskInstance();
        testTask.WhatId=TestAccount.id;
        testTask.Process_Path_Task_Detail__c=testPPTD.id;
        insert testTask; 
        
        // Call the method to test
        Child_components_Controller.UpdateTasks(new List<Id>{testTask.Id}, testTask.Id);
        
        // Perform assertions if needed
    }
    
    @isTest
    static void testUpdateComment() {
        // Create test data
        Process_Path__c  testPP= new Process_Path__c();
        testPP.Name='1234';
        testPP.isActive__c=true;
        insert testPP;
        String WhatId;
        Process_Path_Task_Detail__c testPPTD = new Process_Path_Task_Detail__c();
        testPPTD.isActive__c=true;
        testPPTD.Process_Path__c=testPP.id;
        
        Account TestAccount =TestUtility.createaccountInstance();
        TestAccount.Product_Bussiness_Line__c='NU Score';
        insert TestAccount ;
        task testTask2=TestUtility.CreateTaskInstance();
        insert testTask2;
        task testTask=TestUtility.CreateTaskInstance();
        testTask.WhatId=TestAccount.id;
        testTask.Parent_Task_Id__c=testTask2.id;
        testTask.Process_Path_Task_Detail__c=testPPTD.id;
        insert testTask; 
        
        
        
        // Call the method to test
        Task result = Child_components_Controller.updateComment(testTask);
        
        // Perform assertions
        //System.assertNotEquals(null, result, 'Expected a non-null result');
        // Add more assertions based on the expected behavior of the method
    }
    
    /* @isTest
static void testGetFinancialAccId() {
// Create test data
String opportunityId =;  // Replace with a valid Opportunity Id

// Call the method to test
String result = Child_components_Controller.getFinancialAccId(opportunityId);

// Perform assertions
System.assertNotEquals(null, result, 'Expected a non-null result');
// Add more assertions based on the expected behavior of the method
} */
    
    @isTest
    static void testUpsertPRCF() {
        List<Process_Review_Checklist_FACT__c> prcfRecords = new List<Process_Review_Checklist_FACT__c>();
        prcfRecords.add(new Process_Review_Checklist_FACT__c(Comments__c = 'Test PRCF'));

        Test.startTest();
        List<Process_Review_Checklist_FACT__c> results = Child_components_Controller.upsert_PRCF(prcfRecords);
        Test.stopTest();

        // Assertions to check the upsert operation
        System.assertNotEquals(null, results, 'Results should not be null');
        //System.assertEquals(1, results.size(), 'There should be one record');
        //System.assertEquals('Test PRCF', results[0].Comments__c, 'Name should match the test record');
    }
    
    private static Account createTestAccount() {
        Account testAccount = TestUtility.createaccountInstance();
        insert testAccount;
        return testAccount;
        
    }
    
     
     private static Financial_Account__c createTestFinancialAccount(Account testAccount) {
        // Correctly create and insert an Opportunity
        Opportunity opp = TestUtility.CreateOppINstance();
        insert opp; // Inserts the Opportunity to generate a valid ID

        // Create and insert Financial_Account__c with correct references to Account and Opportunity IDs
        Financial_Account__c fa = new Financial_Account__c(
            Opportunity__c = opp.Id,
            Name = 'Test Financial Account',
            Account_Name__c = testAccount.Id // Assign the Account ID to the lookup field
           // Borrower_Name__c = 'Test Borrower'
        );
        insert fa;
        return fa;
    }

    @isTest
    static void testGetFinancialAccId() {
        Account testAccount = createTestAccount();
        Financial_Account__c fa = createTestFinancialAccount(testAccount);
        Test.startTest();
        Financial_Account__c result = Child_components_Controller.getFinancialAccId(fa.Opportunity__c);
        Test.stopTest();
        
        // Assertions to ensure correct data retrieval
        System.assert(result != null, 'Financial Account should not be null');
        System.assertEquals('Test Financial Account', result.Name);
        System.assertEquals(testAccount.Id, result.Account_Name__c, 'Account ID should match the test Account');
    }
    
    
}