force-app/main/default/objects/Account/fields/Product_Bussiness_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Bussiness_Line__c</fullName>
    <defaultValue>&apos;Not Assigned&apos;</defaultValue>
    <description>To populate the value of business Line from which the account was created</description>
    <label>Product Bussiness Line</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DO</fullName>
            </value>
            <value>
                <fullName>NU Score</fullName>
            </value>
            <value>
                <fullName>Nimbus</fullName>
            </value>
            <value>
                <fullName>SCF</fullName>
            </value>
            <value>
                <fullName>CLM</fullName>
            </value>
            <value>
                <fullName>EL</fullName>
            </value>
            <value>
                <fullName>LAP</fullName>
            </value>
            <value>
                <fullName>Shipping</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Under Onboarding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Handler__c/Document_Handler__c.object-meta.xml
<CustomObject>
    <label>Document Handler</label>
    <nameField>
        <label>Document Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Handler</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Handler__c/fields/Document_Metadata__c.field-meta.xml
<CustomField>
    <fullName>Document_Metadata__c</fullName>
    <label>Document Metadata</label>
    <referenceTo>Document_Metadata__c</referenceTo>
    <relationshipLabel>Document Handler</relationshipLabel>
    <relationshipName>Document_Handler</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Document_Handler__c/fields/Document_Sharing_Task_Ids__c.field-meta.xml
<CustomField>
    <fullName>Document_Sharing_Task_Ids__c</fullName>
    <label>Document Sharing Task Ids</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Handler__c/fields/Extended_SObject_RecordId__c.field-meta.xml
<CustomField>
    <fullName>Extended_SObject_RecordId__c</fullName>
    <label>Extended SObject RecordId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Handler__c/fields/Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Financial_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Account</label>
    <referenceTo>Financial_Account__c</referenceTo>
    <relationshipLabel>Document Handler</relationshipLabel>
    <relationshipName>Document_Handler</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Handler__c/fields/MODT_Details__c.field-meta.xml
<CustomField>
    <fullName>MODT_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MODT Details</label>
    <referenceTo>MODT_Details__c</referenceTo>
    <relationshipLabel>Document Handler</relationshipLabel>
    <relationshipName>Document_Handler</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Handler__c/fields/Process_Attribute_Dcoument_Detail__c.field-meta.xml
<CustomField>
    <fullName>Process_Attribute_Dcoument_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Process Attribute Dcoument Detail</label>
    <referenceTo>Process_Attribute_Dcoument_Detail__c</referenceTo>
    <relationshipLabel>Document Handler</relationshipLabel>
    <relationshipName>Document_Handler</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Handler__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dispatched</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>To Be Dispatched</fullName>
            </value>
            <value>
                <fullName>Not Received</fullName>
            </value>
            <value>
                <fullName>Submited For Review</fullName>
            </value>
            <value>
                <fullName>Deviation Approved</fullName>
            </value>
            <value>
                <fullName>Deviation Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted for Deviation Approval</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Uploaded</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Re-Assigned</fullName>
            </value>
            <value>
                <fullName>Handed Over Successfully</fullName>
            </value>
            <value>
                <fullName>To Be Handed Over</fullName>
            </value>
            <value>
                <fullName>Submit For Review</fullName>
            </value>
            <value>
                <fullName>Change of Payment Mode</fullName>
            </value>
            <value>
                <fullName>Wrong Check Details</fullName>
            </value>
            <value>
                <fullName>Exempted</fullName>
            </value>
            <value>
                <fullName>Physical Document Pending</fullName>
            </value>
            <value>
                <fullName>Document Storage</fullName>
            </value>
            <value>
                <fullName>Physically Stored</fullName>
            </value>
            <value>
                <fullName>Memo Executed</fullName>
            </value>
            <value>
                <fullName>Submitted For Execution</fullName>
            </value>
            <value>
                <fullName>Alternate Document Added</fullName>
            </value>
            <value>
                <fullName>Request Cancellation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Handler__c/fields/Task_Id__c.field-meta.xml
<CustomField>
    <fullName>Task_Id__c</fullName>
    <label>Task Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Handler__c/fields/Transfer_By__c.field-meta.xml
<CustomField>
    <fullName>Transfer_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transfer By</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Document Handler (Transfer By)</relationshipLabel>
    <relationshipName>DH_Transfer_By</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Handler__c/fields/Transfer_To__c.field-meta.xml
<CustomField>
    <fullName>Transfer_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transfer To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Document Handler</relationshipLabel>
    <relationshipName>DH_Transfer_To</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Metadata__c/Document_Metadata__c.object-meta.xml
<CustomObject>
    <label>Process Document Metadata</label>
    <nameField>
        <label>Document Metadata Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Document Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Account__c/Financial_Account__c.object-meta.xml
<CustomObject>
    <description>To store the financial account details of Loan and Insurance</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Individual/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Individuals</relationshipLabel>
    <relationshipName>Individuals</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MODT_Details__c/MODT_Details__c.object-meta.xml
<CustomObject>
    <label>MODT Details</label>
    <nameField>
        <displayFormat>MODT-{00000000}</displayFormat>
        <label>MODT Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MODT Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MODT_Details__c/fields/Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Financial_Account__c</fullName>
    <label>Financial Account</label>
    <referenceTo>Financial_Account__c</referenceTo>
    <relationshipLabel>MODT Details</relationshipLabel>
    <relationshipName>MODT_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MODT_Details__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>MODT Created</fullName>
            </value>
            <value>
                <fullName>MODT Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Paybale__c/Paybale__c.object-meta.xml
<CustomObject>
    <label>Payable</label>
    <nameField>
        <label>Paybales Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Paybales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Paybale__c/fields/Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Financial_Account__c</fullName>
    <label>Financial Account</label>
    <referenceTo>Financial_Account__c</referenceTo>
    <relationshipName>Paybales</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Paybale__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Memo Created</fullName>
            </value>
            <value>
                <fullName>Memo Cancelled</fullName>
            </value>
            <value>
                <fullName>Accepted By Bank</fullName>
            </value>
            <value>
                <fullName>Submitted For Execution</fullName>
            </value>
            <value>
                <fullName>Request Cancellation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Process_Attribute_Dcoument_Detail__c/Process_Attribute_Dcoument_Detail__c.object-meta.xml
<CustomObject>
    <label>Process Attribute Dcoument Detail</label>
    <nameField>
        <label>Process Attribute Dcoument Detail</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Attribute Dcoument Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Process_Attribute_Dcoument_Detail__c/fields/Document_Metadata__c.field-meta.xml
<CustomField>
    <fullName>Document_Metadata__c</fullName>
    <label>Document Metadata</label>
    <referenceTo>Document_Metadata__c</referenceTo>
    <relationshipLabel>Process Attribute Dcoument Details</relationshipLabel>
    <relationshipName>Process_Attribute_Dcoument_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Process_Attribute_Dcoument_Detail__c/fields/Document_Name__c.field-meta.xml
<CustomField>
    <fullName>Document_Name__c</fullName>
    <formula>Document_Metadata__r.Document_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Document Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DocumentCourierDetailControllerTest.cls
@isTest(SeeAllData=false)
private class DocumentCourierDetailControllerTest {
    @isTest
    static void testGetDocumentCourierDetails() {  
        Account userAccDet = new Account(Name = 'Test User Account', Product_Bussiness_Line__c='NU Score');
        insert userAccDet;
        Contact testContact = new Contact(LastName = 'Test Contact', AccountId = userAccDet.Id, IsActive__c = true);
        insert testContact;
        Individual testIndividual = TestUtility.createIndividulaInstance();
        testIndividual.AccountId__c = userAccDet.id;
        insert testIndividual;
        User testUser = TestUtility.createUserInstance();
        testUser.IndividualId = testIndividual.id;
        insert testUser;

        Task testTaskData = TestUtility.CreateTaskInstance();
        insert testTaskData;

        Document_MetaData__c testDMD = TestUtility.createDocumentMetadata();
        insert testDMD;
        Financial_Account__c testFA = TestUtility.createFinancialAccountInstance();
        //insert testFA;
        Paybale__c testMEMO = TestUtility.createMODTInstance();
        //testMEMO.Financial_Account__c = testFA.id;
        //insert testMEMO;
        
        MODT_Details__c ModtDetails = TestUtility.CreateMODTDetailInsatance();
        ModtDetails.Task_Id__c = testTaskData.id;
        insert ModtDetails;
        
        Process_Attribute_Dcoument_Detail__c ProcessAtributeDocDetail = TestUtility.ProcessAttributeDocumentDetailInstance();
        Insert ProcessAtributeDocDetail;
        
        
        List<Document_Handler__c> documentHandlers = new List<Document_Handler__c>();
        
        
        Document_Handler__c testDocumentHandler = new Document_Handler__c(
            Status__c = 'Dispatched',
            Transfer_By__c = userAccDet.id,
            Transfer_to__c = userAccDet.Id,
            Document_Metadata__c = testDMD.id,
            Tracking_Number__c = '2345678',
            Extended_SObject_RecordId__c = testMEMO.id,
            Document_Sharing_Task_Ids__c = testTaskData.Id
        );
  
        documentHandlers.add(testDocumentHandler);
        Document_Handler__c testDocumentHandlerModt = new Document_Handler__c(
            Status__c = 'Dispatched',  
            Transfer_By__c = userAccDet.id,
            Transfer_to__c = userAccDet.Id,
            Document_Metadata__c = testDMD.id,
            Tracking_Number__c = '23456781',
            Extended_SObject_RecordId__c = ModtDetails.id,
            Document_Sharing_Task_Ids__c = testTaskData.Id
        );
        
        
        documentHandlers.add(testDocumentHandlerModt);
        
        Document_Handler__c testDocumentHandlerName = new Document_Handler__c(
            Status__c = 'Dispatched', 
            Document_Name__c = 'Test',
            Transfer_By__c = userAccDet.id,
            Transfer_to__c = userAccDet.Id,
            Document_Metadata__c = testDMD.id,
            Tracking_Number__c = '23456781',
            Extended_SObject_RecordId__c = ModtDetails.id,
            Document_Sharing_Task_Ids__c = testTaskData.Id
        );
        
        
        documentHandlers.add(testDocumentHandlerName);
        
        
        Document_Handler__c testDocumentHandlertatusTBH = new Document_Handler__c(
            Status__c = 'To Be Handed Over', 
            Document_Name__c = 'Cheque',
            Transfer_By__c = userAccDet.id,
            Transfer_to__c = userAccDet.Id,
            Document_Metadata__c = testDMD.id,
            Tracking_Number__c = '23456781',
            Extended_SObject_RecordId__c = ModtDetails.id,
            Document_Sharing_Task_Ids__c = testTaskData.Id
        );
        
        
        documentHandlers.add(testDocumentHandlertatusTBH);
		
        insert documentHandlers;

        System.runAs(testUser) {
            Test.startTest();
            system.debug('testUser.id===>'+testUser.id);
            DocumentCourierDetailController.wrapperforDocuments result = DocumentCourierDetailController.getDocumentCourierDetails(testTaskData);
            DocumentCourierDetailController.wrapperforDocuments result1 = DocumentCourierDetailController.docsWithdetails(testTaskData);
            DocumentCourierDetailController.wrapperforDocuments result2 = DocumentCourierDetailController.docsWithdetailsforStorage(testTaskData);
            Test.stopTest();
            System.assertNotEquals(null, result);
            System.assertNotEquals(null, result.documents);
        }
    }


    @isTest
    static void testMarkAsReceived() {
        User testUser = TestUtility.createUserInstance();
        insert testUser;

        Task testTaskData = TestUtility.createTaskInstance();
        insert testTaskData;

        Document_MetaData__c testDMD = TestUtility.createDocumentMetadata();
        insert testDMD;
        Document_Handler__c testDH = TestUtility.createDocumentHandlerInstance();
        testDH.Document_Metadata__c = testDMD.id;
        testDH.Status__c = 'Dispatched';
        insert testDH;
        List<String> documentIds = new List<String>{testDH.Id};
        
        Test.startTest();
        String result = DocumentCourierDetailController.markAsReceived(documentIds);
        Test.stopTest();

        System.assertEquals('success', result);
        Document_Handler__c updatedDH = [SELECT Status__c FROM Document_Handler__c WHERE Id = :testDH.Id];
        System.assertEquals('Received', updatedDH.Status__c);
    }

    @isTest
    static void testDocsWithdetails() {
        User testUser = TestUtility.createUserInstance();
        //insert testUser;
        Task testTask = TestUtility.createTaskInstance();
        insert testTask;

       /* Test.startTest();
        DocumentCourierDetailController.wrapperforDocuments result = DocumentCourierDetailController.docsWithdetails(testTask);
        Test.stopTest();*/

        //System.assertNotEquals(null, result);
    }

    @isTest
    static void testUpdateDocumentRecord() {
        User testUser = TestUtility.createUserInstance();
        insert testUser;

        Document_MetaData__c testDMD = TestUtility.createDocumentMetadata();
        insert testDMD;
        Document_Handler__c testDH = TestUtility.createDocumentHandlerInstance();
        testDH.Document_Metadata__c = testDMD.id;
        insert testDH;

        testDH.Status__c = 'Received';
        testDH.Comment_History__c = 'Updated Comment';
        List<Document_Handler__c> documentsToUpdate = new List<Document_Handler__c>{testDH};

        Test.startTest();
        DocumentCourierDetailController.updateDocumentRecord(documentsToUpdate);
        Test.stopTest();

        Document_Handler__c updatedDH = [SELECT Status__c, Comment_History__c FROM Document_Handler__c WHERE Id = :testDH.Id];
        System.assertEquals('Received', updatedDH.Status__c);
        System.assertNotEquals(null, updatedDH.Comment_History__c);
    }
    
    private static Task createTestTask() {
        Task newTask = new Task(
            Subject = 'Test Task',
            Status = 'Open'
        );
        insert newTask;
        return newTask;
    }

    // Test method for successful task retrieval
    @isTest static void testGetTaskRecordByIdSuccess() {
        Task testTask = createTestTask();

        // Call the method with the ID of the inserted task
        Task retrievedTask = DocumentCourierDetailController.getTaskRecirdbyId(testTask.Id);

        // Assertions to check that the retrieved task matches the inserted task
        System.assertNotEquals(null, retrievedTask, 'Task should not be null');
        System.assertEquals(testTask.Id, retrievedTask.Id, 'The IDs should match');
        System.assertEquals('Test Task', retrievedTask.Subject, 'The subject should match');
    }

    // Test method to handle invalid task ID
    @isTest static void testGetTaskRecordByIdWithInvalidId() {
        String fakeId = '000000000000AAA'; // Non-existent ID
        Test.startTest();
        try {
            Task retrievedTask = DocumentCourierDetailController.getTaskRecirdbyId(fakeId);
            System.assert(false, 'Exception should have been thrown');
        } catch (QueryException e) {
            System.assert(e.getMessage().contains('List has no rows for assignment to SObject'), 'Expected no rows for assignment exception');
        }
        Test.stopTest();
    }
    
    
}