force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Under Onboarding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Callout_Audit__c/API_Callout_Audit__c.object-meta.xml
<CustomObject>
    <label>API Callout Audit</label>
    <nameField>
        <displayFormat>ACA-{00000}</displayFormat>
        <label>API Callout Audit</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Callout Audit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/API_Callout_Audit__c/fields/API_Status__c.field-meta.xml
<CustomField>
    <fullName>API_Status__c</fullName>
    <label>API Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Callout_Audit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Awaiting</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Handler__c/Document_Handler__c.object-meta.xml
<CustomObject>
    <label>Document Handler</label>
    <nameField>
        <label>Document Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Handler</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Handler__c/fields/Document_Metadata__c.field-meta.xml
<CustomField>
    <fullName>Document_Metadata__c</fullName>
    <label>Document Metadata</label>
    <referenceTo>Document_Metadata__c</referenceTo>
    <relationshipLabel>Document Handler</relationshipLabel>
    <relationshipName>Document_Handler</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Document_Handler__c/fields/Extended_SObject_RecordId__c.field-meta.xml
<CustomField>
    <fullName>Extended_SObject_RecordId__c</fullName>
    <label>Extended SObject RecordId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Handler__c/fields/Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Financial_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Account</label>
    <referenceTo>Financial_Account__c</referenceTo>
    <relationshipLabel>Document Handler</relationshipLabel>
    <relationshipName>Document_Handler</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Handler__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dispatched</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>To Be Dispatched</fullName>
            </value>
            <value>
                <fullName>Not Received</fullName>
            </value>
            <value>
                <fullName>Submited For Review</fullName>
            </value>
            <value>
                <fullName>Deviation Approved</fullName>
            </value>
            <value>
                <fullName>Deviation Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted for Deviation Approval</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Uploaded</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Re-Assigned</fullName>
            </value>
            <value>
                <fullName>Handed Over Successfully</fullName>
            </value>
            <value>
                <fullName>To Be Handed Over</fullName>
            </value>
            <value>
                <fullName>Submit For Review</fullName>
            </value>
            <value>
                <fullName>Change of Payment Mode</fullName>
            </value>
            <value>
                <fullName>Wrong Check Details</fullName>
            </value>
            <value>
                <fullName>Exempted</fullName>
            </value>
            <value>
                <fullName>Physical Document Pending</fullName>
            </value>
            <value>
                <fullName>Document Storage</fullName>
            </value>
            <value>
                <fullName>Physically Stored</fullName>
            </value>
            <value>
                <fullName>Memo Executed</fullName>
            </value>
            <value>
                <fullName>Submitted For Execution</fullName>
            </value>
            <value>
                <fullName>Alternate Document Added</fullName>
            </value>
            <value>
                <fullName>Request Cancellation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Handler__c/fields/Task_Id__c.field-meta.xml
<CustomField>
    <fullName>Task_Id__c</fullName>
    <label>Task Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Metadata__c/Document_Metadata__c.object-meta.xml
<CustomObject>
    <label>Process Document Metadata</label>
    <nameField>
        <label>Document Metadata Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Document Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Account__c/Financial_Account__c.object-meta.xml
<CustomObject>
    <description>To store the financial account details of Loan and Insurance</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Account__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Loan Amount Applied</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/Originating_Branch__c.field-meta.xml
<CustomField>
    <fullName>Originating_Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Originating Branch</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Accounts (Originating Branch)</relationshipLabel>
    <relationshipName>Financial_Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Entity_AC_Detail__c/Financial_Entity_AC_Detail__c.object-meta.xml
<CustomObject>
    <label>Financial Entity AC Detail</label>
    <nameField>
        <label>Financial Entity AC Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Entity AC Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Entity_AC_Detail__c/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Financial_Entity_AC_Detail__c/fields/Bank_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Type__c</fullName>
    <label>Bank Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Savings</fullName>
            </value>
            <value>
                <fullName>Current</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Financial_Entity_AC_Detail__c/fields/Banking_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Banking_Account_Name__c</fullName>
    <label>Banking Account Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Financial_Entity_AC_Detail__c/fields/Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Financial_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Account</label>
    <referenceTo>Financial_Account__c</referenceTo>
    <relationshipLabel>Financial Entity AC Details</relationshipLabel>
    <relationshipName>Financial_Entity_AC_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IDFC_Payout_Metadata__mdt/IDFC_Payout_Metadata__mdt.object-meta.xml
<CustomObject>
    <label>IDFC Payout Metadata</label>
    <pluralLabel>IDFC Payout Metadatas</pluralLabel>
</CustomObject>

force-app/main/default/objects/IDFC_Payout_Metadata__mdt/fields/Matching_Type__c.field-meta.xml
<CustomField>
    <fullName>Matching_Type__c</fullName>
    <label>Matching Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IDFC_Payout_Metadata__mdt/fields/Purpose_Code__c.field-meta.xml
<CustomField>
    <fullName>Purpose_Code__c</fullName>
    <label>Purpose Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Paybale__c/Paybale__c.object-meta.xml
<CustomObject>
    <label>Payable</label>
    <nameField>
        <label>Paybales Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Paybales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Paybale__c/fields/Execution_Request_Document_Handler__c.field-meta.xml
<CustomField>
    <fullName>Execution_Request_Document_Handler__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Execution Request Document Handler</label>
    <referenceTo>Document_Handler__c</referenceTo>
    <relationshipLabel>Paybales</relationshipLabel>
    <relationshipName>Paybales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Paybale__c/fields/Execution_Request_Processed__c.field-meta.xml
<CustomField>
    <fullName>Execution_Request_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Execution Request Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Paybale__c/fields/Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Financial_Account__c</fullName>
    <label>Financial Account</label>
    <referenceTo>Financial_Account__c</referenceTo>
    <relationshipName>Paybales</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Paybale__c/fields/Financial_Entity_A_C_Details__c.field-meta.xml
<CustomField>
    <fullName>Financial_Entity_A_C_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Entity A/C Details</label>
    <referenceTo>Financial_Entity_AC_Detail__c</referenceTo>
    <relationshipName>Paybales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Paybale__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Payable_Payee_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>RTGS</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>UPI</fullName>
            </value>
            <value>
                <fullName>Sanction Amount</fullName>
            </value>
            <value>
                <fullName>Waiver</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Paybale__c/fields/Payable_File_Name__c.field-meta.xml
<CustomField>
    <fullName>Payable_File_Name__c</fullName>
    <formula>Financial_Account__r.Name + &apos;-&apos;+ RIGHT(Id,2)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payable File Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Paybale__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Memo Created</fullName>
            </value>
            <value>
                <fullName>Memo Cancelled</fullName>
            </value>
            <value>
                <fullName>Accepted By Bank</fullName>
            </value>
            <value>
                <fullName>Submitted For Execution</fullName>
            </value>
            <value>
                <fullName>Request Cancellation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SendPayableDetailsToCustomer.cls
public class SendPayableDetailsToCustomer {
    
    Public static AuditResponseWrapperClass sendPayableDetails(Id taskRecordId){
        String auditResult = Label.AuditAPIFailedStatus;
        system.debug('taskRecordId::'+taskRecordId);
        List<Document_Handler__c> docHandlerList 	= new List<Document_Handler__c>();
        List<Paybale__c> payableList 				= new List<Paybale__c>();
        List<Document_Handler__c> docHanlderTobeUpdate = new List<Document_Handler__c>();
        List<IDFC_Payout_Metadata__mdt> payoutMetaDataList = new List<IDFC_Payout_Metadata__mdt>();
        Map<String,IDFC_Payout_Metadata__mdt> mapOfCompareValueByResultValue = new Map<String,IDFC_Payout_Metadata__mdt>();
        AuditResponseWrapperClass auditResponse = new AuditResponseWrapperClass();
        auditResponse.auditRec = new API_Callout_Audit__c();
        try{
            Id dependantTaskRecordId = [select Id,Execution_Depended_Closed_Task_Ids__c,Parent_Task_Id__c from Task where Id =: taskRecordId].Parent_Task_Id__c;
            payoutMetaDataList = [SELECT Id,Compare_Value__c,Matching_Type__c,Purpose_Code__c from IDFC_Payout_Metadata__mdt];
            
            if(!payoutMetaDataList.isEMpty()){
                for(IDFC_Payout_Metadata__mdt idfcPayout : payoutMetaDataList){
                    mapOfCompareValueByResultValue.put(idfcPayout.Compare_Value__c,idfcPayout);
                }
            }
            //ID nextDependantTaskId = [select Id,Execution_Depended_on_Task_Ids__c from task where Parent_Task_Id__c =: taskRecordId].Id;
            system.debug('dependantTaskRecordId::'+dependantTaskRecordId);
            Set<Id> payableIdSet = new Set<Id>();
            Map<ID,Paybale__c> mapofPayableIdByDet = new Map<ID,Paybale__c>();
            system.debug('docHandlerList::'+taskRecordId);
            
            payableList		= [SELECT Id,Value_Date__c,Amount__C,Financial_Entity_A_C_Details__c,Financial_Entity_A_C_Details__r.Bank_Account_Number__c,
                               Financial_Account__r.Name,Payable_File_Name__c,Financial_Entity_A_C_Details__r.Banking_Account_Name__c,
                               Financial_Entity_A_C_Details__r.IFSC_Code__c,Mode__c,Task_Id__c,Financial_Entity_A_C_Details__r.Bank_Account_Type__c,
                               Financial_Account__r.Originating_Branch__r.Name	  
                               FROM Paybale__c 
                               Where Task_Id__c =: dependantTaskRecordId and Status__c =: Constants.PAYABLE_STATUS_MEMO_CREATED and Execution_Request_Processed__c = false];
            
            system.debug('payableList::'+payableList);
            if(!payableList.isEmpty()){
                for(Paybale__c payRec : payableList){
                    payRec.Status__c = Constants.DOC_HANDLER_SUBMITTED_FOR_EXECUTION;
                    payRec.Execution_Request_Processed__c = true;
                    mapofPayableIdByDet.put(payRec.Id,payRec);
                    
                }
                
                
                docHanlderTobeUpdate = [SELECT Id,Extended_SObject_RecordId__c
                                        from Document_Handler__c 
                                        where Extended_SObject_RecordId__c in: mapofPayableIdByDet.keySet()];
                
                String csvContent = 'Client Code,Debit Account No,Transaction Type Code,Value Date,Amount,Beneficary Name,Beneficary Accunt no.,IFSC code,Customer Ref no.,Beneficary email id,Beneficary mobile no.,Remarks,Payment Type,Purpose code,Bene a/c type,Payable Location,Print Branch Name,Mode of delivery,Transaction currency,BENE_ADD1,BENE_ADD2,BENE_ADD3,BENE_ADD4\n'; // Replace with actual field names
                
                // Add data rows
                for (Paybale__c payRec : payableList) {
                    system.debug('payRec::'+payRec);
                    if(payRec.Value_Date__c == null){
                        payRec.Value_Date__c = system.today();
                    }
                    if(payRec.Financial_Entity_A_C_Details__r.IFSC_Code__c == null){
                        payRec.Financial_Entity_A_C_Details__r.IFSC_Code__c = '';
                    }
                    if(payRec.Financial_Entity_A_C_Details__r.Banking_Account_Name__c == null){
                        payRec.Financial_Entity_A_C_Details__r.Banking_Account_Name__c = '';
                    }
                    String clientCode = 'NACLCH';
                    String transactionTypeCode = 'CC';
                    String paymentType = '';
                    String purposeCode = '';
                    String accountType = '';
                    String deliveryMode = 'BP'; 
                    String transactionType = 'INR';
                    if(!mapOfCompareValueByResultValue.isEMpty()){
                        if(mapOfCompareValueByResultValue.containsKey('NACL') && payRec.Mode__c != 'Cheque'){
                            clientCode = mapOfCompareValueByResultValue.get('NACL').Matching_Type__c;
                        }
                        if(mapOfCompareValueByResultValue.containsKey(payRec.Mode__c)){
                            transactionTypeCode = mapOfCompareValueByResultValue.get(payRec.Mode__c).Matching_Type__c;
                        }
                        system.debug('payRec.Mode__c::'+payRec.Mode__c);
                        if(payRec.Mode__c != 'Cheque' && (payRec.Mode__c == 'RTGS' || payRec.Mode__c == 'NEFT')){
                            
                            
                            if(mapOfCompareValueByResultValue.containsKey(payRec.Mode__c)){
                                paymentType = mapOfCompareValueByResultValue.get(payRec.Mode__c).Compare_Value__c;//Validate
                            }
                            
                            if(mapOfCompareValueByResultValue.containsKey(payRec.Mode__c)){
                                purposeCode = mapOfCompareValueByResultValue.get(payRec.Mode__c).Purpose_Code__c;//Validate
                            }
                        }
                        if(mapOfCompareValueByResultValue.containsKey(payRec.Financial_Entity_A_C_Details__r.Bank_Account_Type__c)){
                            accountType = mapOfCompareValueByResultValue.get(payRec.Financial_Entity_A_C_Details__r.Bank_Account_Type__c).Matching_Type__c;
                        }
                        
                        
                        
                    }
                    
                    
                    csvContent += '"' + String.valueOf(clientCode).escapeCsv() + '","' +//Client Code
                        String.valueOf(payRec.Financial_Entity_A_C_Details__r.Bank_Account_Number__c).escapeCsv() + '","' +//Debit Account No
                        String.valueOf(transactionTypeCode).escapeCsv() + '","' +//Transaction Type Code
                        String.valueOf(payRec.Value_Date__c).escapeCsv() + '","' +//Value Date
                        String.ValueOf(payRec.Amount__c).escapeCsv() + '","' +//Amount
                        payRec.Financial_Entity_A_C_Details__r.Banking_Account_Name__c.escapeCsv() + '","';//Ben Name
                    system.debug('CSV1111:::'+csvContent);
                    if((payRec.Mode__c == 'RTGS' || payRec.Mode__c == 'NEFT')){
                        csvContent += String.valueOf(payRec.Financial_Entity_A_C_Details__r.Bank_Account_Number__c).escapeCsv() + '","' +//Ben Account No
                            payRec.Financial_Entity_A_C_Details__r.IFSC_Code__c.escapeCsv() + '","';//IFSC Code
                    }else{
                        csvContent += + '","'+
                            + '","' ;
                    }
                    system.debug('CSV2222:::'+csvContent);
                    csvContent += String.valueOf(payRec.Payable_File_Name__c).escapeCsv() + '","' +//Customer ref No
                        + '","' +  // Beneficary Email Id
                        + '","' + // beneficary Mobile No.
                        + '","' ; // Remarks
                    if(payRec.Mode__c == 'RTGS' || payRec.Mode__c == 'NEFT'){
                        csvContent += String.valueOf(payRec.Mode__C.escapeCsv())  + '","' +//payment type
                            String.valueOf(purposeCode).escapeCsv()  + '","' ;//Purpose Code
                    }else{
                        csvContent += + '","' +
                            + '","' ;  
                    }
                    system.debug('CSV333:::'+csvContent);
                    csvContent += '","' + // Beneficary Account Type
                        + '","' + // Payable Location
                        + '","' + // Print Branch Name
                        String.valueOf(deliveryMode).escapeCsv()  + '","' +//Mode of delivery
                        String.valueOf(transactionType).escapeCsv()  + '","' ;//Transaction Currency
                    if(payRec.Mode__c == 'Cheque'){
                        csvContent +=  'Northern Arc Capital'.escapeCsv()  + '","' +//,
                            String.valueOf(payRec.Financial_Account__r.Originating_Branch__r.Name).escapeCsv()  + '","' + 
                            + '","' +
                            String.valueOf(payRec.Financial_Account__r.Name).escapeCsv()  + '","' +
                            + '","' +  '"\n';
                        
                    }else{
                        csvContent +=  + '","' + // BENE_ADD1
                            + '","' + //BENE_ADD2
                            + '","' + //BENE_ADD3
                            + '","' + //BENE_ADD4
                            + '","' +  '"\n';
                    }
                    
                    system.debug('CSV444:::'+csvContent);
                }
                
                // Convert CSV string to Blob
                Document_Handler__c docHandler = new Document_Handler__c();
                Document_Metadata__c docMetaRec = [select id,Document_Name__c from Document_Metadata__c where Document_Name__c='MEMO Submitted For Request' limit 1];
                system.debug('docMetaRec::'+docMetaRec);
                docHandler.Task_Id__c = taskRecordId;
                docHandler.Status__c = 'Completed';
                docHandler.Document_Metadata__c = docMetaRec.Id;
                insert docHandler;
                system.debug('docHandler::'+docHandler);
                ContentVersion file = new ContentVersion(
                    title = 'PayableAccount.csv'+taskRecordId,
                    versionData = Blob.valueOf( csvContent ),
                    pathOnClient = '/PayableAccounts.csv',
                    FirstPublishLocationId = docHandler.Id
                );
                insert file;
                for(Paybale__c payRec : payableList){
                    payRec.Execution_Request_Document_Handler__c = docHandler.Id;
                }
                update payableList;
                system.debug('file::'+file);
                auditResponse = EmailService.ExecuteEmailServices(taskRecordId,docHandler.Id);
                if(!docHanlderTobeUpdate.isEmpty()){
                    for(Document_Handler__c docHandlerRec : docHanlderTobeUpdate){
                        docHandlerRec.Status__c = Constants.DOC_HANDLER_SUBMITTED_FOR_EXECUTION;
                    }
                    
                    update docHanlderTobeUpdate;
                }
                //update payableList;
            }
            auditResponse.auditRec.API_Status__c = Label.AuditAPIStatus;
            auditResult = Label.AuditAPIStatus;
        }catch(Exception e){
            system.debug('exception::'+e);
            system.debug('exception line::'+e.getStackTraceString());
            auditResponse.auditRec.Response__c = e.getStackTraceString();
            auditResponse.auditRec.API_Status__c = Label.AuditAPIFailedStatus;
        }
        
        return auditResponse;
        
    }
}