force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Under Onboarding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Handler__c/Document_Handler__c.object-meta.xml
<CustomObject>
    <label>Document Handler</label>
    <nameField>
        <label>Document Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Handler</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Handler__c/fields/Current_Task_ID__c.field-meta.xml
<CustomField>
    <fullName>Current_Task_ID__c</fullName>
    <label>Current Task ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Handler__c/fields/Document_Sharing_Task_Ids__c.field-meta.xml
<CustomField>
    <fullName>Document_Sharing_Task_Ids__c</fullName>
    <label>Document Sharing Task Ids</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Handler__c/fields/Process_Attribute_Dcoument_Detail__c.field-meta.xml
<CustomField>
    <fullName>Process_Attribute_Dcoument_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Process Attribute Dcoument Detail</label>
    <referenceTo>Process_Attribute_Dcoument_Detail__c</referenceTo>
    <relationshipLabel>Document Handler</relationshipLabel>
    <relationshipName>Document_Handler</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Handler__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dispatched</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>To Be Dispatched</fullName>
            </value>
            <value>
                <fullName>Not Received</fullName>
            </value>
            <value>
                <fullName>Submited For Review</fullName>
            </value>
            <value>
                <fullName>Deviation Approved</fullName>
            </value>
            <value>
                <fullName>Deviation Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted for Deviation Approval</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Uploaded</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Re-Assigned</fullName>
            </value>
            <value>
                <fullName>Handed Over Successfully</fullName>
            </value>
            <value>
                <fullName>To Be Handed Over</fullName>
            </value>
            <value>
                <fullName>Submit For Review</fullName>
            </value>
            <value>
                <fullName>Change of Payment Mode</fullName>
            </value>
            <value>
                <fullName>Wrong Check Details</fullName>
            </value>
            <value>
                <fullName>Exempted</fullName>
            </value>
            <value>
                <fullName>Physical Document Pending</fullName>
            </value>
            <value>
                <fullName>Document Storage</fullName>
            </value>
            <value>
                <fullName>Physically Stored</fullName>
            </value>
            <value>
                <fullName>Memo Executed</fullName>
            </value>
            <value>
                <fullName>Submitted For Execution</fullName>
            </value>
            <value>
                <fullName>Alternate Document Added</fullName>
            </value>
            <value>
                <fullName>Request Cancellation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Handler__c/fields/Task_Id__c.field-meta.xml
<CustomField>
    <fullName>Task_Id__c</fullName>
    <label>Task Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Process_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Process_Attribute__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Attribute</label>
    <referenceTo>Process_Attribute__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Process_Attribute__c/Process_Attribute__c.object-meta.xml
<CustomObject>
    <description>To define the master records of case/lead/sales/collection processes</description>
    <label>Process Attribute</label>
    <nameField>
        <label>Attribute ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Process_Attribute__c/fields/Process_Attribute_Path_Deviation__c.field-meta.xml
<CustomField>
    <fullName>Process_Attribute_Path_Deviation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Default Path Deviation</label>
    <referenceTo>Process_Attribute_Path_Deviation__c</referenceTo>
    <relationshipLabel>Process Attributes</relationshipLabel>
    <relationshipName>Process_Attributes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Process_Attribute__c/fields/Process_Path__c.field-meta.xml
<CustomField>
    <fullName>Process_Path__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Default Process Path</label>
    <referenceTo>Process_Path__c</referenceTo>
    <relationshipLabel>Process Attributes</relationshipLabel>
    <relationshipName>Process_Attributes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Process_Attribute_Dcoument_Detail__c/Process_Attribute_Dcoument_Detail__c.object-meta.xml
<CustomObject>
    <label>Process Attribute Dcoument Detail</label>
    <nameField>
        <label>Process Attribute Dcoument Detail</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Attribute Dcoument Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Process_Attribute_Dcoument_Detail__c/fields/Process_Path__c.field-meta.xml
<CustomField>
    <fullName>Process_Path__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Process Path</label>
    <referenceTo>Process_Path__c</referenceTo>
    <relationshipLabel>Process Attribute Dcoument Details</relationshipLabel>
    <relationshipName>Process_Attribute_Dcoument_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Process_Attribute_Dcoument_Detail__c/fields/Process_Path_Task_Detail__c.field-meta.xml
<CustomField>
    <fullName>Process_Path_Task_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Process Path Task Detail</label>
    <referenceTo>Process_Path_Task_Detail__c</referenceTo>
    <relationshipLabel>Process Attribute Dcoument Details</relationshipLabel>
    <relationshipName>Process_Attribute_Dcoument_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Process_Attribute_Path_Deviation__c/Process_Attribute_Path_Deviation__c.object-meta.xml
<CustomObject>
    <label>Process Attribute Path Deviation</label>
    <nameField>
        <label>Process Attribute Path Deviation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Attribute Path Deviations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Process_Attribute_Path_Deviation__c/fields/Document_Sharing_Status__c.field-meta.xml
<CustomField>
    <fullName>Document_Sharing_Status__c</fullName>
    <label>Document Sharing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Document_Handler_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Process_Attribute_Path_Deviation__c/fields/Process_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Process_Attribute__c</fullName>
    <label>Process Attribute</label>
    <referenceTo>Process_Attribute__c</referenceTo>
    <relationshipLabel>Process Attribute Path Deviations</relationshipLabel>
    <relationshipName>Process_Attribute_Path_Deviations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Process_Attribute_Path_Deviation__c/fields/Process_Path__c.field-meta.xml
<CustomField>
    <fullName>Process_Path__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Process Path Tobe Initiated</label>
    <referenceTo>Process_Path__c</referenceTo>
    <relationshipLabel>Process Attribute Path Deviations</relationshipLabel>
    <relationshipName>Process_Attribute_Path_Deviations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Process_Attribute_Path_Deviation__c/fields/Process_Path_Type__c.field-meta.xml
<CustomField>
    <fullName>Process_Path_Type__c</fullName>
    <label>Process Path Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Process_Path_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Process_Path__c/Process_Path__c.object-meta.xml
<CustomObject>
    <description>Junction Object to be used to refer Process Path Detail (PAD) for Process Attribute</description>
    <label>Process Path</label>
    <nameField>
        <label>Process Path ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Paths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Process_Path_Task_Detail__c/Process_Path_Task_Detail__c.object-meta.xml
<CustomObject>
    <label>Process Path Task Detail</label>
    <nameField>
        <label>Process Path Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Path Task Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Process_Path_Task_Detail__c/fields/Business_Step_No__c.field-meta.xml
<CustomField>
    <fullName>Business_Step_No__c</fullName>
    <label>Business Step No</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Process_Path_Task_Detail__c/fields/Execution_Serial_No__c.field-meta.xml
<CustomField>
    <fullName>Execution_Serial_No__c</fullName>
    <label>Execution Serial No</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SL_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Process_Path_Task_Detail__c/fields/Process_Path__c.field-meta.xml
<CustomField>
    <fullName>Process_Path__c</fullName>
    <label>Process Path</label>
    <referenceTo>Process_Path__c</referenceTo>
    <relationshipLabel>Process Path Task Details</relationshipLabel>
    <relationshipName>Process_Path_Task_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Process_Path_Task_Detail__c/fields/Process_Task_Detail__c.field-meta.xml
<CustomField>
    <fullName>Process_Task_Detail__c</fullName>
    <label>Process Task Detail</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Process_Task_Detail__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Process_Task_Detail__c</referenceTo>
    <relationshipLabel>Process Path Task Details</relationshipLabel>
    <relationshipName>Process_Path_Task_Details</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Process_Path_Task_Detail__c/fields/Task_Owner_Name__c.field-meta.xml
<CustomField>
    <fullName>Task_Owner_Name__c</fullName>
    <label>Task Owner Name</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Process_Task_Detail__c/Process_Task_Detail__c.object-meta.xml
<CustomObject>
    <label>Process Task Detail</label>
    <nameField>
        <label>Process Task Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Task Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Process_Task_Document_Sharing__c/Process_Task_Document_Sharing__c.object-meta.xml
<CustomObject>
    <label>Process Task Document Sharing</label>
    <nameField>
        <label>Process Task Document Sharing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Task Documents Sharing</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Process_Task_Document_Sharing__c/fields/Process_Attribute_Dcoument_Detail__c.field-meta.xml
<CustomField>
    <fullName>Process_Attribute_Dcoument_Detail__c</fullName>
    <label>Process Attribute Dcoument Detail</label>
    <referenceTo>Process_Attribute_Dcoument_Detail__c</referenceTo>
    <relationshipLabel>Process Task Documents Sharing</relationshipLabel>
    <relationshipName>Process_Task_Documents_Sharing</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Process_Task_Document_Sharing__c/fields/Process_Task_Detail__c.field-meta.xml
<CustomField>
    <fullName>Process_Task_Detail__c</fullName>
    <label>Process Task Detail</label>
    <referenceTo>Process_Task_Detail__c</referenceTo>
    <relationshipLabel>Process Task Documents Sharing</relationshipLabel>
    <relationshipName>Process_Task_Documents_Sharing</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestTaskDocumentSharing.cls
@isTest
private class TestTaskDocumentSharing {

    @testSetup
    static void setup() {
        
        // Create test accounts, contacts, and leads to use with tasks
        List<Account> accounts = new List<Account>{ 
            TestUtility.createTestAccount(),
                TestUtility.createTestAccount()
                };
                    
        
        List<Contact> contacts = new List<Contact>{ 
            TestUtility.CreateContactInstance()
                };
                    insert contacts;
        
        List<Lead> leads = new List<Lead>{ 
            TestUtility.CreateLeadInstance()
                };
                    insert leads;
        
        List<Process_Attribute__c> processAttributes = new List<Process_Attribute__c>{
            TestUtility.createProAttributeInstance(),
                TestUtility.createProAttributeInstance()
                };
                    processAttributes[0].Name = 'Process Attribute 1';
        processAttributes[1].Name = 'Process Attribute 2';
        insert processAttributes;
        
        Process_Attribute_Path_Deviation__c processAttributePD = new Process_Attribute_Path_Deviation__c();
        processAttributePD.Document_Sharing_Status__c = 'Approved';
        processAttributePD.Process_Path_Type__c = 'Adhoc Path';
        processAttributePD.Process_Attribute__c = processAttributes[0].Id; 
        
        insert processAttributePD;
        Process_Path__c pptest = TestUtility.createProcessPAthInstance();
        insert pptest;
        
        Process_Task_Detail__c ptdTest =TestUtility.createPTDinstance();
        insert ptdTest;
        
        Process_Path_Task_Detail__c PPTD =  TestUtility.createPPTD();
        pptd.Process_Path__c = pptest.id;
        pptd.Process_Task_Detail__c = ptdTest.id;
        pptd.Business_Step_No__c = 1;
        pptd.Execution_Serial_No__c ='1';
        pptd.Task_Owner_Name__c = 'mukesh';
        insert PPTD;
        
        List<Process_Attribute_Dcoument_Detail__c> docDetails = new List<Process_Attribute_Dcoument_Detail__c>{
            TestUtility.ProcessAttributeDocumentDetailInstance(),
                TestUtility.ProcessAttributeDocumentDetailInstance()
                };
                    insert docDetails;
        system.debug('docDetails::'+docDetails);
        
        List<Task> tasks = new List<Task>{
            TestUtility.createTestTaskWithAttribute('Test Attribute Value 1'),
                TestUtility.createTestTaskWithAttribute('Test Attribute Value 2')
                };
                    tasks[0].WhatId = accounts[0].Id;
        tasks[0].Process_Attribute__c = processAttributes[0].Id;
        tasks[0].Process_Path_Task_Detail__c = PPTD.id;
        tasks[0].Process_Attribute_Path_Deviation__c = processAttributePD.Id;
        //tasks[0].Process_Attribute_Object_Type__c = 'Lead';
        tasks[1].WhoId = contacts[0].Id;
        tasks[1].Process_Attribute__c = processAttributes[1].Id;
        tasks[1].Process_Attribute_Path_Deviation__c = processAttributePD.Id;
        tasks[1].Process_Path_Task_Detail__c = PPTD.id;
        insert tasks;
        
        List<Document_Handler__c> docHandlers = new List<Document_Handler__c>{
            TestUtility.createDocumentHandlerInstance(),
                TestUtility.createDocumentHandlerInstance()
                };
                    docHandlers[0].Task_Id__c = tasks[0].Id;
        docHandlers[0].Process_Attribute_Dcoument_Detail__c = docDetails[0].Id;
        docHandlers[0].Document_Sharing_Task_Ids__c = tasks[0].Id + ',' + tasks[1].Id;
        docHandlers[0].status__c = 'Approved';
        docHandlers[0].Current_Task_ID__c = tasks[0].Id;
        
        docHandlers[1].Task_Id__c = tasks[1].Id;
        docHandlers[1].Process_Attribute_Dcoument_Detail__c = docDetails[1].Id;
        docHandlers[1].Document_Sharing_Task_Ids__c = tasks[1].Id.toString();
        docHandlers[1].status__c = 'Status2';
        docHandlers[1].Current_Task_ID__c = tasks[1].Id;
        insert docHandlers;
        system.debug('docHandlers[0].Process_Attribute_Dcoument_Detail__c'+docHandlers[0].Process_Attribute_Dcoument_Detail__c);
       	system.debug('docHandlers[1].Process_Attribute_Dcoument_Detail__c'+docHandlers[1].Process_Attribute_Dcoument_Detail__c);

        
        tasks[0].Process_Share_Document_Task_Ids__c = docHandlers[0].Current_Task_ID__c;
         tasks[1].Process_Share_Document_Task_Ids__c = docHandlers[1].Current_Task_ID__c;
        update tasks;
        
        List<Process_Task_Document_Sharing__c> sharings = new List<Process_Task_Document_Sharing__c>{
            new Process_Task_Document_Sharing__c(),
                new Process_Task_Document_Sharing__c()
                };
                    sharings[0].Process_Attribute_Dcoument_Detail__c = docDetails[0].Id;
        sharings[0].Process_Task_Detail__c = TestUtility.createMockProcessTaskDetail().Id; // Assuming TestUtility.createMockProcessTaskDetail() returns inserted instances
        sharings[1].Process_Attribute_Dcoument_Detail__c = docDetails[1].Id;
        sharings[1].Process_Task_Detail__c = TestUtility.createMockProcessTaskDetail().Id; // Same assumption as above
        insert sharings;
    }



    @isTest
    static void testTaskDocumentSharing() {
        Test.startTest();
        
        // Query the tasks created in the setup
        List<Task> tasks = [SELECT Id, WhatId, WhoId,Process_Path_Task_Detail__c,Process_Task_Detail__c,Process_Attribute_Object_Type__c,Process_Attribute__c,Process_Attribute_Path_Deviation__c,Process_Share_Document_Task_Ids__c FROM Task];
        system.debug('tasks::'+tasks[0].Process_Attribute_Object_Type__c);

        // Call the invocable method
        TaskDocumentSharing.TaskDocumentSharing(tasks);

        Test.stopTest();

        // Add more data manipulation or method calls if necessary to cover more code within TaskDocumentSharing
        // Note: No assertions are being used as per the instruction
    }
}