force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Under Onboarding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Admin.recordType-meta.xml
<RecordType>
    <fullName>Admin</fullName>
    <active>true</active>
    <label>Admin</label>
</RecordType>

force-app/main/default/objects/Communication_Template__c/Communication_Template__c.object-meta.xml
<CustomObject>
    <label>Communication Template</label>
    <nameField>
        <displayFormat>CT-{000}</displayFormat>
        <label>Communication Template</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communication Template</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Communication_Template__c/fields/Attachment_Query__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Query__c</fullName>
    <label>Attachment Query</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Communication_Template__c/fields/Email_From__c.field-meta.xml
<CustomField>
    <fullName>Email_From__c</fullName>
    <label>Email From</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Communication_Template__c/fields/Email_Service__c.field-meta.xml
<CustomField>
    <fullName>Email_Service__c</fullName>
    <label>Email Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Email_Services</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Communication_Template__c/fields/Email_To__c.field-meta.xml
<CustomField>
    <fullName>Email_To__c</fullName>
    <label>Email To</label>
    <length>75000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Communication_Template__c/fields/Template_Body_Query__c.field-meta.xml
<CustomField>
    <fullName>Template_Body_Query__c</fullName>
    <label>Template Body Query</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Document_Handler__c/Document_Handler__c.object-meta.xml
<CustomObject>
    <label>Document Handler</label>
    <nameField>
        <label>Document Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Handler</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Handler__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Document Associated with which Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Document Handler (Account)</relationshipLabel>
    <relationshipName>Document_Handler</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Handler__c/fields/Document_Metadata__c.field-meta.xml
<CustomField>
    <fullName>Document_Metadata__c</fullName>
    <label>Document Metadata</label>
    <referenceTo>Document_Metadata__c</referenceTo>
    <relationshipLabel>Document Handler</relationshipLabel>
    <relationshipName>Document_Handler</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Document_Handler__c/fields/Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Financial_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Account</label>
    <referenceTo>Financial_Account__c</referenceTo>
    <relationshipLabel>Document Handler</relationshipLabel>
    <relationshipName>Document_Handler</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Handler__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Document Handler</relationshipLabel>
    <relationshipName>Document_Handler</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Handler__c/fields/Task_Id__c.field-meta.xml
<CustomField>
    <fullName>Task_Id__c</fullName>
    <label>Task Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/Financial_Account__c.object-meta.xml
<CustomObject>
    <description>To store the financial account details of Loan and Insurance</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Account__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>Financial_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Loan Amount Applied</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/EMI_Amount__c.field-meta.xml
<CustomField>
    <fullName>EMI_Amount__c</fullName>
    <label>EMI Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/First_EMI_Date__c.field-meta.xml
<CustomField>
    <fullName>First_EMI_Date__c</fullName>
    <label>First EMI Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/LMS_Application_ID__c.field-meta.xml
<CustomField>
    <fullName>LMS_Application_ID__c</fullName>
    <label>LMS Application ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>Financial_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/Sanction_Date__c.field-meta.xml
<CustomField>
    <fullName>Sanction_Date__c</fullName>
    <label>Sanction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/Sanctioned_Amount__c.field-meta.xml
<CustomField>
    <fullName>Sanctioned_Amount__c</fullName>
    <label>Sanctioned Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/Tenuer__c.field-meta.xml
<CustomField>
    <fullName>Tenuer__c</fullName>
    <label>Tenuer</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/recordTypes/Loan.recordType-meta.xml
<RecordType>
    <fullName>Loan</fullName>
    <active>true</active>
    <label>Loan</label>
</RecordType>

force-app/main/default/objects/Process_Path_Task_Detail__c/Process_Path_Task_Detail__c.object-meta.xml
<CustomObject>
    <label>Process Path Task Detail</label>
    <nameField>
        <label>Process Path Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Path Task Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Process_Path_Task_Detail__c/fields/Action_Type__c.field-meta.xml
<CustomField>
    <fullName>Action_Type__c</fullName>
    <label>Action Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Component</fullName>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>System Flow Executed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Process_Path_Task_Detail__c/fields/Action_URL__c.field-meta.xml
<CustomField>
    <fullName>Action_URL__c</fullName>
    <label>Action URL</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Process_Path_Task_Detail__c/fields/Business_Step_No__c.field-meta.xml
<CustomField>
    <fullName>Business_Step_No__c</fullName>
    <label>Business Step No</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Process_Path_Task_Detail__c/fields/Communication_Template__c.field-meta.xml
<CustomField>
    <fullName>Communication_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Communication Template</label>
    <referenceTo>Communication_Template__c</referenceTo>
    <relationshipLabel>Process Path Task Details</relationshipLabel>
    <relationshipName>Process_Path_Task_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Process_Path_Task_Detail__c/fields/Execution_Serial_No__c.field-meta.xml
<CustomField>
    <fullName>Execution_Serial_No__c</fullName>
    <label>Execution Serial No</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SL_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Process_Path_Task_Detail__c/fields/Process_Path__c.field-meta.xml
<CustomField>
    <fullName>Process_Path__c</fullName>
    <label>Process Path</label>
    <referenceTo>Process_Path__c</referenceTo>
    <relationshipLabel>Process Path Task Details</relationshipLabel>
    <relationshipName>Process_Path_Task_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Process_Path_Task_Detail__c/fields/Process_Task_Detail__c.field-meta.xml
<CustomField>
    <fullName>Process_Task_Detail__c</fullName>
    <label>Process Task Detail</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Process_Task_Detail__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Process_Task_Detail__c</referenceTo>
    <relationshipLabel>Process Path Task Details</relationshipLabel>
    <relationshipName>Process_Path_Task_Details</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Process_Path_Task_Detail__c/fields/Task_Owner_Name__c.field-meta.xml
<CustomField>
    <fullName>Task_Owner_Name__c</fullName>
    <label>Task Owner Name</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Process_Path_Task_Detail__c/fields/Task_Owner_Type__c.field-meta.xml
<CustomField>
    <fullName>Task_Owner_Type__c</fullName>
    <label>Task Owner Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Task_Owner_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Process_Path_Task_Detail__c/fields/Task_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Task_Record_Type__c</fullName>
    <label>Task_Record_Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Task_Record_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Process_Task_Detail__c/Process_Task_Detail__c.object-meta.xml
<CustomObject>
    <label>Process Task Detail</label>
    <nameField>
        <label>Process Task Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Task Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Process_Task_Detail__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subject</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Process_Task_Detail__c/fields/Task_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Task_Record_Type__c</fullName>
    <label>Task Record Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Task_Record_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestWelcomeLetterEmailFlow.cls
@IsTest
public class TestWelcomeLetterEmailFlow {
	@IsTest
    public static void SendemaiaTestClass(){
        String parentRecId = '';
        String sObjectId = '';
        Account acc = new Account();
        acc.Name = 'Test Name';
        insert acc;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'test opportunity';
        opp.CloseDate = system.today();
        opp.StageName = 'Closed Won';
        opp.Type = 'LAP Loan Application';
        opp.AccountId = acc.Id;
        insert opp; 
        sObjectId = opp.Id;
        
        Financial_Account__c faAccount = new Financial_Account__c();
        faAccount.Account_Name__c = acc.Id;
        faAccount.Amount__c = 5000;
        faAccount.EMI_Amount__c = 300;
        faAccount.First_EMI_Date__c = system.today();
        faAccount.Opportunity__c = opp.Id;
        insert faAccount;
        
        Communication_Template__c ctRec = new Communication_Template__c();
        ctRec.Email_From__c  = 'kispanchal86@gmail.com';
        ctRec.Email_To__c = 'kispanchal86@gmail.com';
        ctRec.Is_Active__c = true;
        ctRec.Template_Body__c = 'Test Body';
        ctRec.Email_Service__c = 'Salesforce';
        ctRec.Subject__c = 'test Subject';
        ctRec.Attachment_Query__c = 'SELECT Id From Document_Handler__c Where Task_Id__c =: parentRecId';
        ctRec.Template_Body_Query__c = 'SELECT Id,LMS_Application_ID__c,Sanction_Date__c,Sanctioned_Amount__c,Name,Tenuer__c,First_EMI_Date__c,EMI_Amount__c From Financial_Account__c where Opportunity__c =: sObjectId';
        insert ctRec;
        
        Process_path__c testpp = new Process_Path__c();
        testpp.name = 'Memo Execution Request Path';
        testpp.isActive__c = true;
        insert testpp;
        Process_Task_Detail__c testPTD = new Process_Task_Detail__c();
        testPTD.Name = 'Memo Execution Request';
        testPTD.Subject__c	 = 'Memo Execution Request';
        testPTD.Task_Record_Type__c = 'Admin';
        testPTD.IsActive__c = true;
        insert testPTD;
        
        Process_Path_Task_Detail__c testPPTD= new Process_Path_Task_Detail__c();
        testPPTD.name = 'Memo Execution Request Path : T1';
        testPPTD.Communication_Template__c = ctRec.Id;
        testPPTD.Process_Path__c = testpp.Id;
        testPPTD.Subject__c = 'Memo Execution Request';
        testPPTD.Process_Task_Detail__c = testPTD.Id;
        testPPTD.isActive__c = true;
        testPPTD.Task_Record_Type__c = 'API Call Out';
        testPPTD.Action_URL__c = 'SendPayableDetailsToCustomer';
        testPPTD.Action_Type__c = 'Apex';
        testPPTD.Task_Owner_Type__c = 'System';
        testPPTD.Task_Owner_Name__c = 'N/A';
        testPPTD.Business_Step_No__c = 1;
        testPPTD.Execution_Serial_No__c = String.valueOf(1);
        
        insert testPPTD;
        
        Task parentTask = new Task();
        parentTask.Process_Path_Task_Detail__c = testPPTD.Id;
        parentTask.WhatId = opp.Id;
        parentTask.ActivityDate = system.today();
        parentTask.Subject = 'test subject';
        insert parentTask;
        Document_Metadata__c docMetaRec = new Document_Metadata__c();
        docMetaRec.Name = 'Welcome Letter';
        docMetaRec.Document_Name__c = 'Welcome Letter';
        insert docMetaRec;
        //Document_Metadata__c docMetaRec = [select id,Document_Name__c from Document_Metadata__c where Document_Name__c='Welcome Letter' limit 1];
        Document_Handler__c doHandler = new Document_Handler__c();
        doHandler.Account__c = acc.Id;
        doHandler.Task_Id__c = parentTask.Id;
        doHandler.Document_Metadata__c = docMetaRec.Id;
        insert doHandler;
        parentRecId = parentTask.Id;
        Task taskDet = new Task();
        taskDet.Process_Path_Task_Detail__c = testPPTD.Id;
        taskDet.WhatId = opp.Id;
        taskDet.ActivityDate = system.today();
        taskDet.Subject = 'test subject';
        taskDet.Process_Path_Deviation_Initiated_Task_Id__c = parentTask.Id;
        insert taskDet;
        
        API_Callout_Audit__c auditRec = new API_Callout_Audit__c();
        auditRec.Status__c = 'New';
        auditRec.Task_ID__c = taskDet.Id;
        auditRec.Apex_Action__c = 'EmailService';
        insert auditRec;
        
        ContentVersion cv = new ContentVersion();
        cv.Title = 'Test File';
        cv.PathOnClient = 'Test_File.pdf'; // Name of the file
        cv.VersionData = Blob.valueOf('Test file content'); // Content of the file
        cv.IsMajorVersion = true;
        cv.ContentLocation = 'S'; // S indicates that the file is stored in Salesforce
        cv.FirstPublishLocationId = doHandler.Id; // Link the file to the Account
        insert cv;
        
        SystemExecutedMasterClass.FlowInput input = new SystemExecutedMasterClass.FlowInput();
        input.recordId = auditRec.Id;
        input.actionName = 'EmailService';
        input.taskRecordId = taskDet.Id;
        
        SystemExecutedMasterClass.processRecords(new List<SystemExecutedMasterClass.FlowInput>{ input });
        
    }
    
    private static SystemExecutedMasterClass.FlowInput prepareFlowInput(String actionName, Id recordId, Id taskRecordId) {
        SystemExecutedMasterClass.FlowInput input = new SystemExecutedMasterClass.FlowInput();
        input.recordId = recordId;
        input.actionName = actionName;
        input.taskRecordId = taskRecordId;
        return input;
    }
}