force-app/main/default/objects/Communication_Template__c/Communication_Template__c.object-meta.xml
<CustomObject>
    <label>Communication Template</label>
    <nameField>
        <displayFormat>CT-{000}</displayFormat>
        <label>Communication Template</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communication Template</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Communication_Template__c/fields/Attachment_Query__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Query__c</fullName>
    <label>Attachment Query</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Communication_Template__c/fields/CC_Addresses__c.field-meta.xml
<CustomField>
    <fullName>CC_Addresses__c</fullName>
    <label>CC Addresses</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Communication_Template__c/fields/Email_From__c.field-meta.xml
<CustomField>
    <fullName>Email_From__c</fullName>
    <label>Email From</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Communication_Template__c/fields/Email_To__c.field-meta.xml
<CustomField>
    <fullName>Email_To__c</fullName>
    <label>Email To</label>
    <length>75000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Communication_Template__c/fields/Template_Body_Query__c.field-meta.xml
<CustomField>
    <fullName>Template_Body_Query__c</fullName>
    <label>Template Body Query</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Template_Merge_Field__c/Template_Merge_Field__c.object-meta.xml
<CustomObject>
    <label>Template Merge Field</label>
    <nameField>
        <label>Template Merge Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Template Merge Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Template_Merge_Field__c/fields/Communication_Template__c.field-meta.xml
<CustomField>
    <fullName>Communication_Template__c</fullName>
    <label>Communication Template</label>
    <referenceTo>Communication_Template__c</referenceTo>
    <relationshipLabel>Template Merge Fields</relationshipLabel>
    <relationshipName>Template_Merge_Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Template_Merge_Field__c/fields/Merge_Field__c.field-meta.xml
<CustomField>
    <fullName>Merge_Field__c</fullName>
    <label>Merge Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EmailHandler.cls
public class EmailHandler {
    
    public static AuditResponseWrapperClass SendEmailWithSalesforce(Task taskDetail,String parentDocId){
        String parentRecId = '';
        String sObjectId = taskDetail.whatId;
        String templateBody = '';
        if(taskDetail.Process_Path_Task_Detail__r.Communication_Template__c != null && taskDetail.Process_Path_Task_Detail__r.Communication_Template__r.Template_Body__c != null)
            templateBody = (string) taskDetail.Process_Path_Task_Detail__r.Communication_Template__r.Template_Body__c;
        if(parentDocId == '' && taskDetail.Process_Path_Deviation_Initiated_Task_Id__c != null){
            if(taskDetail.Process_Path_Deviation_Initiated_Task_Id__c.contains(',')){
                parentRecId = taskDetail.Process_Path_Deviation_Initiated_Task_Id__c.split(',')[0];
            }else{
                parentRecId = taskDetail.Process_Path_Deviation_Initiated_Task_Id__c;
            }
            
        }else{
            parentRecId = parentDocId;
        }
        
        List<Template_Merge_Field__c> templateMergeFields = new List<Template_Merge_Field__c>();
        List<String> toAddress = new List<String>();
        templateMergeFields = [SELECT Id,Merge_Field__c,Value__c 
                               From Template_Merge_Field__c 
                               WHERE Is_Active__c = true 
                               and Communication_Template__c =: taskDetail.Process_Path_Task_Detail__r.Communication_Template__c];
        
        if(parentRecId != '' && taskDetail.Process_Path_Task_Detail__r.Communication_Template__c != null && taskDetail.Process_Path_Task_Detail__r.Communication_Template__r.Attachment_Query__c != null){
            String v_query = (string) taskDetail.Process_Path_Task_Detail__r.Communication_Template__r.Attachment_Query__c;
            system.debug('v_query::'+v_query);
            sObject r_Parent_RecDetails = Database.query(v_query);
            system.debug('r_Parent_RecDetails::'+r_Parent_RecDetails);
            parentRecId = (String)r_Parent_RecDetails.get('Id');
        }
        
        if(taskDetail.Process_Path_Task_Detail__r.Communication_Template__c != null && taskDetail.Process_Path_Task_Detail__r.Communication_Template__r.Template_Body_Query__c != null){
            
            String v_query = (string) taskDetail.Process_Path_Task_Detail__r.Communication_Template__r.Template_Body_Query__c;
            sObject r_ObjectRecord = Database.query(v_query);
            
            for(Template_Merge_Field__c tmf : templateMergeFields){
                system.debug('tmf.Merge_Field__c::'+tmf.Merge_Field__c);
                system.debug('String.valueOf(r_ObjectRecord.get(tmf.Value__c))::'+String.valueOf(r_ObjectRecord.get(tmf.Value__c)));
                templateBody = templateBody.replace('{!' + tmf.Merge_Field__c +'}',String.valueOf(r_ObjectRecord.get(tmf.Value__c)));
            }
        }
        
        if(taskDetail.Process_Path_Task_Detail__r.Communication_Template__r.Email_To__c.contains(',')){
            toAddress = taskDetail.Process_Path_Task_Detail__r.Communication_Template__r.Email_To__c.split(',');
        }else{
            toAddress.add(taskDetail.Process_Path_Task_Detail__r.Communication_Template__r.Email_To__c);
        }
        return EmailService.SendEmailFunction(toAddress,taskDetail.Process_Path_Task_Detail__r.Communication_Template__r.Subject__c,
                                              templateBody,parentRecId,taskDetail.Process_Path_Task_Detail__r.Communication_Template__r.Email_From__c,
                                              taskDetail.Process_Path_Task_Detail__r.Communication_Template__r.CC_Addresses__c);
        //return null;
    }
    
    public static void SendEmailWithNimbus(){
        
    }
}