force-app/main/default/objects/Communication_Template__c/Communication_Template__c.object-meta.xml
<CustomObject>
    <label>Communication Template</label>
    <nameField>
        <displayFormat>CT-{000}</displayFormat>
        <label>Communication Template</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communication Template</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Communication_Template__c/fields/Attachment_Query__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Query__c</fullName>
    <label>Attachment Query</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Communication_Template__c/fields/Email_From__c.field-meta.xml
<CustomField>
    <fullName>Email_From__c</fullName>
    <label>Email From</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Communication_Template__c/fields/Email_Service__c.field-meta.xml
<CustomField>
    <fullName>Email_Service__c</fullName>
    <label>Email Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Email_Services</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Communication_Template__c/fields/Email_To__c.field-meta.xml
<CustomField>
    <fullName>Email_To__c</fullName>
    <label>Email To</label>
    <length>75000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Communication_Template__c/fields/Template_Body_Query__c.field-meta.xml
<CustomField>
    <fullName>Template_Body_Query__c</fullName>
    <label>Template Body Query</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Document_Handler__c/Document_Handler__c.object-meta.xml
<CustomObject>
    <label>Document Handler</label>
    <nameField>
        <label>Document Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Handler</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Handler__c/fields/Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Financial_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Account</label>
    <referenceTo>Financial_Account__c</referenceTo>
    <relationshipLabel>Document Handler</relationshipLabel>
    <relationshipName>Document_Handler</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Handler__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Document Handler</relationshipLabel>
    <relationshipName>Document_Handler</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Handler__c/fields/Task_Id__c.field-meta.xml
<CustomField>
    <fullName>Task_Id__c</fullName>
    <label>Task Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/Financial_Account__c.object-meta.xml
<CustomObject>
    <description>To store the financial account details of Loan and Insurance</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Account__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>Financial_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Loan Amount Applied</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/EMI_Amount__c.field-meta.xml
<CustomField>
    <fullName>EMI_Amount__c</fullName>
    <label>EMI Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/First_EMI_Date__c.field-meta.xml
<CustomField>
    <fullName>First_EMI_Date__c</fullName>
    <label>First EMI Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/LMS_Application_ID__c.field-meta.xml
<CustomField>
    <fullName>LMS_Application_ID__c</fullName>
    <label>LMS Application ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>Financial_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/Sanction_Date__c.field-meta.xml
<CustomField>
    <fullName>Sanction_Date__c</fullName>
    <label>Sanction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/Sanctioned_Amount__c.field-meta.xml
<CustomField>
    <fullName>Sanctioned_Amount__c</fullName>
    <label>Sanctioned Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/Tenuer__c.field-meta.xml
<CustomField>
    <fullName>Tenuer__c</fullName>
    <label>Tenuer</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/recordTypes/Loan.recordType-meta.xml
<RecordType>
    <fullName>Loan</fullName>
    <active>true</active>
    <label>Loan</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Process_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Process_Attribute__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Attribute</label>
    <referenceTo>Process_Attribute__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Admin.recordType-meta.xml
<RecordType>
    <fullName>Admin</fullName>
    <active>true</active>
    <businessProcess>Sales</businessProcess>
    <label>Admin</label>
</RecordType>

force-app/main/default/objects/Process_Attribute__c/Process_Attribute__c.object-meta.xml
<CustomObject>
    <description>To define the master records of case/lead/sales/collection processes</description>
    <label>Process Attribute</label>
    <nameField>
        <label>Attribute ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Process_Attribute__c/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>To identify is the process is active or not</description>
    <label>isActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Process_Attribute__c/fields/Object_Type__c.field-meta.xml
<CustomField>
    <fullName>Object_Type__c</fullName>
    <label>Object Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Object_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Process_Attribute__c/fields/Process_Path__c.field-meta.xml
<CustomField>
    <fullName>Process_Path__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Default Process Path</label>
    <referenceTo>Process_Path__c</referenceTo>
    <relationshipLabel>Process Attributes</relationshipLabel>
    <relationshipName>Process_Attributes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Process_Attribute__c/fields/Sobject_RecordType_Name__c.field-meta.xml
<CustomField>
    <fullName>Sobject_RecordType_Name__c</fullName>
    <defaultValue>&apos;Master&apos;</defaultValue>
    <label>Sobject RecordType Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Do Onboarding</fullName>
            </value>
            <value>
                <fullName>Business Team EL</fullName>
            </value>
            <value>
                <fullName>Business Team AltiFi</fullName>
            </value>
            <value>
                <fullName>Welcome Calling Details - DO</fullName>
            </value>
            <value>
                <fullName>Welcome Calling Details - EL</fullName>
            </value>
            <value>
                <fullName>Welcome Calling Details - LAP</fullName>
            </value>
            <value>
                <fullName>Welcome Calling Details - Altifi</fullName>
            </value>
            <value>
                <fullName>Customer Service Investment</fullName>
            </value>
            <value>
                <fullName>Business Team LAP</fullName>
            </value>
            <value>
                <fullName>NU Score Payment Schedule Creation</fullName>
            </value>
            <value>
                <fullName>Default</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Process_Attribute_Path_Deviation__c/Process_Attribute_Path_Deviation__c.object-meta.xml
<CustomObject>
    <label>Process Attribute Path Deviation</label>
    <nameField>
        <label>Process Attribute Path Deviation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Attribute Path Deviations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Process_Attribute_Path_Deviation__c/fields/Process_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Process_Attribute__c</fullName>
    <label>Process Attribute</label>
    <referenceTo>Process_Attribute__c</referenceTo>
    <relationshipLabel>Process Attribute Path Deviations</relationshipLabel>
    <relationshipName>Process_Attribute_Path_Deviations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Process_Attribute_Path_Deviation__c/fields/Process_Path__c.field-meta.xml
<CustomField>
    <fullName>Process_Path__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Process Path Tobe Initiated</label>
    <referenceTo>Process_Path__c</referenceTo>
    <relationshipLabel>Process Attribute Path Deviations</relationshipLabel>
    <relationshipName>Process_Attribute_Path_Deviations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Process_Attribute_Path_Deviation__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subject</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Process_Path_Task_Detail__c/Process_Path_Task_Detail__c.object-meta.xml
<CustomObject>
    <label>Process Path Task Detail</label>
    <nameField>
        <label>Process Path Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Path Task Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Process_Path_Task_Detail__c/fields/Communication_Template__c.field-meta.xml
<CustomField>
    <fullName>Communication_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Communication Template</label>
    <referenceTo>Communication_Template__c</referenceTo>
    <relationshipLabel>Process Path Task Details</relationshipLabel>
    <relationshipName>Process_Path_Task_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Process_Path_Task_Detail__c/fields/Process_Path__c.field-meta.xml
<CustomField>
    <fullName>Process_Path__c</fullName>
    <label>Process Path</label>
    <referenceTo>Process_Path__c</referenceTo>
    <relationshipLabel>Process Path Task Details</relationshipLabel>
    <relationshipName>Process_Path_Task_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Process_Task_Detail__c/Process_Task_Detail__c.object-meta.xml
<CustomObject>
    <label>Process Task Detail</label>
    <nameField>
        <label>Process Task Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Task Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Process_Task_Detail__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subject</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_TaskCreationNew2.cls
@IsTest
public class Test_TaskCreationNew2 {
	@IsTest
    public static void TaskCreationTestMethod(){
        Process_Attribute__c paRec = new Process_Attribute__C();
        paRec.Name = 'Opp - LAP';
        paRec.isActive__c = true;
        paRec.Sobject_RecordType_Name__c = 'Business Team LAP';
        paRec.Object_Type__c = 'Opportunity';
        insert paRec;
        
        string sObjectId = '';
        Account acc = new Account();
        acc.Name = 'Test Name';
        insert acc;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'test opportunity';
        opp.CloseDate = system.today();
        opp.StageName = 'Closed Won';
        opp.Type = 'LAP Loan Application';
        opp.AccountId = acc.Id;
        opp.Process_Attribute__c = paRec.Id;
        insert opp; 
        sObjectId = opp.Id;
        
        Financial_Account__c faAccount = new Financial_Account__c();
        faAccount.Account_Name__c = acc.Id;
        faAccount.Amount__c = 5000;
        faAccount.EMI_Amount__c = 300;
        faAccount.First_EMI_Date__c = system.today();
        faAccount.Opportunity__c = opp.Id;
        insert faAccount;
        
        Communication_Template__c ctRec = new Communication_Template__c();
        ctRec.Email_From__c  = 'kispanchal86@gmail.com';
        ctRec.Email_To__c = 'kispanchal86@gmail.com';
        ctRec.Is_Active__c = true;
        ctRec.Template_Body__c = 'Test Body';
        ctRec.Email_Service__c = 'Salesforce';
        ctRec.Subject__c = 'test Subject';
        ctRec.Attachment_Query__c = 'SELECT Id From Document_Handler__c Where Task_Id__c =: parentRecId';
        ctRec.Template_Body_Query__c = 'SELECT Id,LMS_Application_ID__c,Sanction_Date__c,Sanctioned_Amount__c,Name,Tenuer__c,First_EMI_Date__c,EMI_Amount__c From Financial_Account__c where Opportunity__c =: sObjectId';
        insert ctRec;
        
        
        
        Process_path__c testDefaultPath = new Process_Path__c();
        testDefaultPath.name = 'Default Path';
        testDefaultPath.isActive__c = true;
        insert testDefaultPath;
        
        Process_Task_Detail__c testStartPTD = new Process_Task_Detail__c();
        testStartPTD.Name = 'Start';
        testStartPTD.Subject__c	 = 'Start';
        testStartPTD.Task_Record_Type__c = 'Admin';
        testStartPTD.IsActive__c = true;
        insert testStartPTD;
        
        
        Process_Path_Task_Detail__c testDeviationStartFromPPTD = new Process_Path_Task_Detail__c();
        testDeviationStartFromPPTD.name = 'Default Path - Start';
        testDeviationStartFromPPTD.Communication_Template__c = ctRec.Id;
        testDeviationStartFromPPTD.Process_Path__c = testDefaultPath.Id;
        testDeviationStartFromPPTD.Execution_Serial_No__c = String.valueOf(1);
        testDeviationStartFromPPTD.Path_No__c = 'P0';
        testDeviationStartFromPPTD.Business_Step_No__c = 1;
        testDeviationStartFromPPTD.Subject__c = 'Start';
        testDeviationStartFromPPTD.isActive__c = true;
        testDeviationStartFromPPTD.Process_Task_Detail__c = testStartPTD.Id;
        testDeviationStartFromPPTD.Task_Record_Type__c = 'API Call Out';
        testDeviationStartFromPPTD.Action_URL__c = 'SendPayableDetailsToCustomer';
        testDeviationStartFromPPTD.Action_Type__c = 'Apex';
        testDeviationStartFromPPTD.Task_Owner_Type__c = 'System';
        testDeviationStartFromPPTD.Task_Owner_Name__c = 'N/A';
        testDeviationStartFromPPTD.Execution_Serial_No__c = String.valueOf(1);
        insert testDeviationStartFromPPTD;
        
        Process_path__c testMainPath = new Process_Path__c();
        testMainPath.name = 'Main Path';
        testMainPath.isActive__c = true;
        insert testMainPath;
        
        Process_Task_Detail__c testMainPTD = new Process_Task_Detail__c();
        testMainPTD.Name = 'Document Collection';
        testMainPTD.Subject__c	 = 'Document Collection';
        testMainPTD.Task_Record_Type__c = 'Admin';
        testMainPTD.IsActive__c = true;
        insert testMainPTD;
        
        Process_Path_Task_Detail__c testDocumentCollectionPPTD = new Process_Path_Task_Detail__c();
        testDocumentCollectionPPTD.name = 'Opp - LAP : Fresh Main Path : T1';
        //testDocumentCollectionPPTD.Communication_Template__c = ctRec.Id;
        testDocumentCollectionPPTD.Process_Path__c = testMainPath.Id;
        testDocumentCollectionPPTD.Execution_Serial_No__c = String.valueOf(1);
        testDocumentCollectionPPTD.Path_No__c = 'P0';
        testDocumentCollectionPPTD.Business_Step_No__c = 1;
        testDocumentCollectionPPTD.Subject__c = 'Start';
        testDocumentCollectionPPTD.isActive__c = true;
        testDocumentCollectionPPTD.Process_Task_Detail__c = testMainPTD.Id;
        testDocumentCollectionPPTD.Task_Record_Type__c = 'Basic Task Layout';
        testDocumentCollectionPPTD.Action_URL__c = 'CMP_TaskMaster';
        testDocumentCollectionPPTD.Action_Type__c = 'Apex';
        testDocumentCollectionPPTD.Task_Owner_Type__c = 'System';
        testDocumentCollectionPPTD.Task_Owner_Name__c = 'N/A';
        testDocumentCollectionPPTD.Execution_Serial_No__c = String.valueOf(1);
        insert testDocumentCollectionPPTD;
        
        Process_path__c testEndPath = new Process_Path__c();
        testEndPath.name = 'End Path';
        testEndPath.isActive__c = true;
        insert testEndPath;
        
        Process_Task_Detail__c testEndPTD = new Process_Task_Detail__c();
        testEndPTD.Name = 'End Path';
        testEndPTD.Subject__c	 = 'End';
        testEndPTD.Task_Record_Type__c = 'Admin';
        testEndPTD.IsActive__c = true;
        insert testEndPTD;
        
        Process_Path_Task_Detail__c testEndPathPPTD = new Process_Path_Task_Detail__c();
        testEndPathPPTD.name = 'End Path';
        //testDocumentCollectionPPTD.Communication_Template__c = ctRec.Id;
        testEndPathPPTD.Process_Path__c = testEndPath.Id;
        testEndPathPPTD.Execution_Serial_No__c = String.valueOf(1);
        testEndPathPPTD.Path_No__c = 'P0';
        testEndPathPPTD.Business_Step_No__c = 1;
        testEndPathPPTD.Subject__c = 'End';
        testEndPathPPTD.isActive__c = true;
        testEndPathPPTD.Process_Task_Detail__c = testEndPTD.Id;
        testEndPathPPTD.Task_Record_Type__c = 'Basic Task Layout';
        testEndPathPPTD.Action_URL__c = 'CMP_TaskMaster';
        testEndPathPPTD.Action_Type__c = 'Apex';
        testEndPathPPTD.Task_Owner_Type__c = 'System';
        testEndPathPPTD.Task_Owner_Name__c = 'N/A';
        testEndPathPPTD.Execution_Serial_No__c = String.valueOf(1);
        insert testEndPathPPTD;
        
        Process_Execution_Condition__c testPEC = new Process_Execution_Condition__c();
        testPEC.Name = 'Opp - LAP : Fresh Main Path Cond';
        insert testPEC;
        
        Process_Execution_Condition_Detail__c testPECD = new Process_Execution_Condition_Detail__c();
        testPECD.Name = 'Opp - LAP : Fresh Main Path Cond. : 1';
        testPECD.Process_Execution_Condition__c = testPEC.Id;
        testPECD.Condition_Expression__c = 'select id from Financial_Account__c where Opportunity__c = :whatid and Loan_Closure_Required__c != true';
        testPECD.Condition_SL_No__c = String.valueOf(1);
        testPECD.Condition_Type__c = 'SOQL';
        
        Process_Attribute_Path_Deviation__c testPAPD = new Process_Attribute_Path_Deviation__c();
        testPAPD.Name = 'Default Path - Start -> Opp - LAP : Fresh Main Path : Dev';
        testPAPD.isActive__c = true;
        testPAPD.Process_Path_Task_Detail_Start__c = testDeviationStartFromPPTD.Id;
        testPAPD.Process_Attribute__c = paRec.Id;
        testPAPD.Process_Path_Type__c = 'Child Path';
        testPAPD.Process_Path__c = testMainPath.Id;
        testPAPD.Process_Path_Task_Detail_End__c = testEndPathPPTD.Id;
        testPAPD.Process_Execution_Condition__c = testPEC.Id;
        testPAPD.Is_Document_Sharing_Path__c = true;
        insert testPAPD;
        
        Task InitiatedTask = new Task();
        InitiatedTask.Subject = 'Start';
        InitiatedTask.Status = 'Draft';
        InitiatedTask.WhatId = opp.Id;
        InitiatedTask.Process_Attribute_Path_Deviation__c = testPAPD.Id;
        InitiatedTask.Process_Attribute__c = paRec.Id;
        InitiatedTask.Process_Path_Task_Detail__c = testDeviationStartFromPPTD.Id;
        InitiatedTask.Process_Path_Deviation_Ids__c = testPAPD.Id;
        Insert InitiatedTask;
        
        Task StartTask = new Task();
        StartTask.Subject = 'Start';
        StartTask.Status = 'Draft';
        StartTask.WhatId = opp.Id;
        StartTask.Process_Attribute_Path_Deviation__c = testPAPD.Id;
        StartTask.Process_Attribute__c = paRec.Id;
        StartTask.Process_Path_Task_Detail__c = testDeviationStartFromPPTD.Id;
        StartTask.Process_Path_Deviation_Ids__c = testPAPD.Id;
        Insert StartTask;
        String tempId = StartTask.Id;
        if(tempId.contains(',')){
           StartTask.Id = tempId.remove(','); 
        }else{
           StartTask.Id = tempId; 
        }
        StartTask.Process_Path_Deviation_Initiated_Task_Id__c = StartTask.Id;
        StartTask.Process_Path_Deviation_End_Task_Id__c = StartTask.Id;
        StartTask.Process_Path_Initiated_Task_Id__c = StartTask.Id;
        update StartTask;
        
        
        task inp_task = new task();
        inp_task.id = StartTask.Id;
        
        TaskCreationNew2.SObjectTaskWrapper cr = new TaskCreationNew2.SObjectTaskWrapper();
        cr.inp_sObject = inp_task;
        
        
        List<TaskCreationNew2.SObjectTaskWrapper> l = new List<TaskCreationNew2.SObjectTaskWrapper>();
        l.add(cr);
        TaskCreationNew2.SObjectNewTaskCreation(l);
        
        opportunity oppinp_task = new opportunity();
        oppinp_task.id = opp.Id;
        
        
        TaskCreationNew2.SObjectTaskWrapper crOpp = new TaskCreationNew2.SObjectTaskWrapper();
        crOpp.inp_sObject = oppinp_task;
        List<TaskCreationNew2.SObjectTaskWrapper> opp1 = new List<TaskCreationNew2.SObjectTaskWrapper>();
        opp1.add(crOpp);
        TaskCreationNew2.SObjectNewTaskCreation(opp1);
    }
}