force-app/main/default/objects/Communication_Template__c/Communication_Template__c.object-meta.xml
<CustomObject>
    <label>Communication Template</label>
    <nameField>
        <displayFormat>CT-{000}</displayFormat>
        <label>Communication Template</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communication Template</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Communication_Template__c/fields/Attachment_Query__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Query__c</fullName>
    <label>Attachment Query</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Communication_Template__c/fields/Email_From__c.field-meta.xml
<CustomField>
    <fullName>Email_From__c</fullName>
    <label>Email From</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Communication_Template__c/fields/Email_Service__c.field-meta.xml
<CustomField>
    <fullName>Email_Service__c</fullName>
    <label>Email Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Email_Services</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Communication_Template__c/fields/Email_To__c.field-meta.xml
<CustomField>
    <fullName>Email_To__c</fullName>
    <label>Email To</label>
    <length>75000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Communication_Template__c/fields/Template_Body_Query__c.field-meta.xml
<CustomField>
    <fullName>Template_Body_Query__c</fullName>
    <label>Template Body Query</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Document_Handler__c/Document_Handler__c.object-meta.xml
<CustomObject>
    <label>Document Handler</label>
    <nameField>
        <label>Document Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Handler</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Handler__c/fields/Document_Metadata__c.field-meta.xml
<CustomField>
    <fullName>Document_Metadata__c</fullName>
    <label>Document Metadata</label>
    <referenceTo>Document_Metadata__c</referenceTo>
    <relationshipLabel>Document Handler</relationshipLabel>
    <relationshipName>Document_Handler</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Document_Handler__c/fields/Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Financial_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Account</label>
    <referenceTo>Financial_Account__c</referenceTo>
    <relationshipLabel>Document Handler</relationshipLabel>
    <relationshipName>Document_Handler</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Handler__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Document Handler</relationshipLabel>
    <relationshipName>Document_Handler</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Handler__c/fields/Task_Id__c.field-meta.xml
<CustomField>
    <fullName>Task_Id__c</fullName>
    <label>Task Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/Financial_Account__c.object-meta.xml
<CustomObject>
    <description>To store the financial account details of Loan and Insurance</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Account__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>Financial_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Loan Amount Applied</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/EMI_Amount__c.field-meta.xml
<CustomField>
    <fullName>EMI_Amount__c</fullName>
    <label>EMI Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/First_EMI_Date__c.field-meta.xml
<CustomField>
    <fullName>First_EMI_Date__c</fullName>
    <label>First EMI Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/LMS_Application_ID__c.field-meta.xml
<CustomField>
    <fullName>LMS_Application_ID__c</fullName>
    <label>LMS Application ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>Financial_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/Sanction_Date__c.field-meta.xml
<CustomField>
    <fullName>Sanction_Date__c</fullName>
    <label>Sanction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/Sanctioned_Amount__c.field-meta.xml
<CustomField>
    <fullName>Sanctioned_Amount__c</fullName>
    <label>Sanctioned Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/Tenuer__c.field-meta.xml
<CustomField>
    <fullName>Tenuer__c</fullName>
    <label>Tenuer</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Financial_Entity__c/Financial_Entity__c.object-meta.xml
<CustomObject>
    <label>Financial Entity</label>
    <nameField>
        <label>Financial Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Entities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Entity__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Entities</relationshipLabel>
    <relationshipName>Financial_Entities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Entity__c/fields/Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Financial_Account__c</fullName>
    <label>Financial Account</label>
    <referenceTo>Financial_Account__c</referenceTo>
    <relationshipLabel>Financial Entities</relationshipLabel>
    <relationshipName>Financial_Entities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Financial_Entity__c/fields/Task_ID__c.field-meta.xml
<CustomField>
    <fullName>Task_ID__c</fullName>
    <label>Task ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Financial_Entity_AC_Detail__c/Financial_Entity_AC_Detail__c.object-meta.xml
<CustomObject>
    <label>Financial Entity AC Detail</label>
    <nameField>
        <label>Financial Entity AC Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Entity AC Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Entity_AC_Detail__c/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Financial_Entity_AC_Detail__c/fields/Bank_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Type__c</fullName>
    <label>Bank Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Savings</fullName>
            </value>
            <value>
                <fullName>Current</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Financial_Entity_AC_Detail__c/fields/Banking_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Banking_Account_Name__c</fullName>
    <label>Banking Account Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Financial_Entity_AC_Detail__c/fields/Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Financial_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Account</label>
    <referenceTo>Financial_Account__c</referenceTo>
    <relationshipLabel>Financial Entity AC Details</relationshipLabel>
    <relationshipName>Financial_Entity_AC_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Entity_AC_Detail__c/fields/Financial_Entity__c.field-meta.xml
<CustomField>
    <fullName>Financial_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Entity</label>
    <referenceTo>Financial_Entity__c</referenceTo>
    <relationshipLabel>Financial Entity AC Details</relationshipLabel>
    <relationshipName>Financial_Entity_AC_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Paybale__c/Paybale__c.object-meta.xml
<CustomObject>
    <label>Payable</label>
    <nameField>
        <label>Paybales Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Paybales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Paybale__c/fields/Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Financial_Account__c</fullName>
    <label>Financial Account</label>
    <referenceTo>Financial_Account__c</referenceTo>
    <relationshipName>Paybales</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Paybale__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Paybales</relationshipLabel>
    <relationshipName>Paybales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Process_Path_Task_Detail__c/Process_Path_Task_Detail__c.object-meta.xml
<CustomObject>
    <label>Process Path Task Detail</label>
    <nameField>
        <label>Process Path Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Path Task Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Process_Path_Task_Detail__c/fields/Communication_Template__c.field-meta.xml
<CustomField>
    <fullName>Communication_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Communication Template</label>
    <referenceTo>Communication_Template__c</referenceTo>
    <relationshipLabel>Process Path Task Details</relationshipLabel>
    <relationshipName>Process_Path_Task_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Process_Path_Task_Detail__c/fields/Process_Path__c.field-meta.xml
<CustomField>
    <fullName>Process_Path__c</fullName>
    <label>Process Path</label>
    <referenceTo>Process_Path__c</referenceTo>
    <relationshipLabel>Process Path Task Details</relationshipLabel>
    <relationshipName>Process_Path_Task_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Process_Task_Detail__c/Process_Task_Detail__c.object-meta.xml
<CustomObject>
    <label>Process Task Detail</label>
    <nameField>
        <label>Process Task Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Task Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Process_Task_Detail__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subject</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestSendPayableDetailsToCustomer.cls
@isTest
private class TestSendPayableDetailsToCustomer {
    
    @isTest
    static void testSendPayableDetails() {
        // Create necessary test data using TestUtility
        Account testAccount = TestUtility.createTestAccount();
        //insert testAccount;
        Opportunity testOpportunity = TestUtility.createTestOpportunity(testAccount.Id);
        insert testOpportunity;
        
        Financial_Account__c faAccount = new Financial_Account__c();
        faAccount.Account_Name__c = testAccount.Id;
        faAccount.Amount__c = 5000;
        faAccount.EMI_Amount__c = 300;
        faAccount.First_EMI_Date__c = system.today();
        faAccount.Opportunity__c = testOpportunity.Id;
        insert faAccount;
        
        Financial_Entity__c FinancialEntity = new Financial_Entity__c();
        
        FinancialEntity.Financial_Account__c =faAccount.Id;
        insert FinancialEntity;
        
        Document_Metadata__c docMetaRec = new Document_Metadata__c();
        docMetaRec.Name = 'MEMO Submitted For Request';
        docMetaRec.Document_Name__c = 'MEMO Submitted For Request';
        insert docMetaRec;
        
        Financial_Entity_AC_Detail__c feac = new Financial_Entity_AC_Detail__c();
        feac.Bank_Account_Number__c = 'Test Bank Account';
        feac.Bank_Account_Type__c = 'Savings';
        feac.Bank_Name__c = 'Axis Bank';
        feac.Banking_Account_Name__c = 'Test Banking Name';
        feac.Financial_Account__c = faAccount.Id;
        feac.Financial_Entity__c = FinancialEntity.Id;
        feac.IFSC_Code__c = 'test IFSC';
        insert  feac;       
        Communication_Template__c ctRec = new Communication_Template__c();
        ctRec.Email_From__c  = 'kispanchal86@gmail.com';
        ctRec.Email_To__c = 'kispanchal86@gmail.com';
        ctRec.Is_Active__c = true;
        ctRec.Template_Body__c = 'Test Body';
        ctRec.Email_Service__c = 'Salesforce';
        ctRec.Subject__c = 'test Subject';
        ctRec.Attachment_Query__c = 'SELECT Id From Document_Handler__c Where Task_Id__c =: parentRecId';
        ctRec.Template_Body_Query__c = 'SELECT Id,LMS_Application_ID__c,Sanction_Date__c,Sanctioned_Amount__c,Name,Tenuer__c,First_EMI_Date__c,EMI_Amount__c From Financial_Account__c where Opportunity__c =: sObjectId';
        insert ctRec;
        
        
        Process_path__c testpp = new Process_Path__c();
        testpp.name = 'Memo Execution Request Path';
        testpp.isActive__c = true;
        insert testpp;
        Process_Task_Detail__c testPTD = new Process_Task_Detail__c();
        testPTD.Name = 'Memo Execution Request';
        testPTD.Subject__c	 = 'Memo Execution Request';
        testPTD.Task_Record_Type__c = 'Admin';
        testPTD.IsActive__c = true;
        insert testPTD;
        
        Process_Path_Task_Detail__c testPPTD= new Process_Path_Task_Detail__c();
        testPPTD.name = 'Memo Execution Request Path : T1';
        testPPTD.Communication_Template__c = ctRec.Id;
        testPPTD.Process_Path__c = testpp.Id;
        testPPTD.Subject__c = 'Memo Execution Request';
        testPPTD.Process_Task_Detail__c = testPTD.Id;
        testPPTD.isActive__c = true;
        testPPTD.Task_Record_Type__c = 'API Call Out';
        testPPTD.Action_URL__c = 'SendPayableDetailsToCustomer';
        testPPTD.Action_Type__c = 'Apex';
        testPPTD.Task_Owner_Type__c = 'System';
        testPPTD.Task_Owner_Name__c = 'N/A';
        testPPTD.Business_Step_No__c = 1;
        testPPTD.Execution_Serial_No__c = String.valueOf(1);
        
        insert testPPTD;
        
        
        Task parentTask = new Task();
        parentTask.Process_Path_Task_Detail__c = testPPTD.Id;
        parentTask.WhatId = testOpportunity.Id;
        parentTask.ActivityDate = system.today();
        parentTask.Subject = 'test subject';
        insert parentTask;
        
        
        Paybale__c testPayable = TestUtility.createMODTInstance();
        //insert testPayable;
        Paybale__c testMEMO = new Paybale__c();
        testMEMO.Amount__c=12345;
        testMEMO.IsActive__c=true;	
        testMEMO.Financial_Account__c=faAccount.id;
        testMEMO.Task_Id__c = parentTask.Id;
        testMEMO.RBI_UTR_Reference_Number__c = '12345';
        testMEMO.Finacial_Entity_Details__c = FinancialEntity.Id;
        testMEMO.Status__c ='Memo Created';
        testMEMO.Financial_Entity_A_C_Details__c =feac.Id;
        testMEMO.Mode__c = 'Cheque';
        insert testMEMO;
        
        testMEMO.Mode__c = 'RTGS';
        update testMEMO;
        
        Task taskDet = new Task();
        taskDet.Process_Path_Task_Detail__c = testPPTD.Id;
        taskDet.WhatId = testOpportunity.Id;
        taskDet.ActivityDate = system.today();
        taskDet.Subject = 'test subject';
        taskDet.Process_Path_Deviation_Initiated_Task_Id__c = parentTask.Id;
        taskDet.Parent_Task_Id__c = parentTask.Id;
        insert taskDet;
        
        Document_Handler__c docHandler = new Document_Handler__c();
        system.debug('docMetaRec::'+docMetaRec);
        docHandler.Task_Id__c = taskDet.id;
        docHandler.Status__c = 'Completed';
        docHandler.Document_Metadata__c = docMetaRec.Id;
        insert docHandler;
        
        // Call the method under test
        Test.startTest();
        SendPayableDetailsToCustomer.sendPayableDetails(taskDet.Id);
        Test.stopTest();
        
        // Assertions would normally go here
    }
    
    
}