force-app/main/default/objects/API_Callout_Audit__c/API_Callout_Audit__c.object-meta.xml
<CustomObject>
    <label>API Callout Audit</label>
    <nameField>
        <displayFormat>ACA-{00000}</displayFormat>
        <label>API Callout Audit</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Callout Audit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/API_Callout_Audit__c/fields/API_Status__c.field-meta.xml
<CustomField>
    <fullName>API_Status__c</fullName>
    <label>API Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Financial_Account__c/Financial_Account__c.object-meta.xml
<CustomObject>
    <description>To store the financial account details of Loan and Insurance</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Account__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>Financial_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/Tenuer__c.field-meta.xml
<CustomField>
    <fullName>Tenuer__c</fullName>
    <label>Tenuer</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Receivable__c/Receivable__c.object-meta.xml
<CustomObject>
    <label>Receivable</label>
    <nameField>
        <label>Receivable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Receivables</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Receivable__c/fields/Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Financial_Account__c</fullName>
    <label>Financial Account</label>
    <referenceTo>Financial_Account__c</referenceTo>
    <relationshipLabel>Receivables</relationshipLabel>
    <relationshipName>Receivables</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/WelcomeLetterHandler.cls
public class WelcomeLetterHandler {
    
    public static AuditResponseWrapperClass WelcomeLetterGenerationFlow(Id taskId){
        Id recordTypeId 	= Schema.SObjectType.Receivable__c.getRecordTypeInfosByName().get('Repayment Schedule').getRecordTypeId();
        String auditResult 	= Label.AuditAPIFailedStatus;
        
        Id opportunity_Id 						= [SELECT Id,WhatId From Task Where Id =: taskId].WhatId;
        Financial_Account__c financial_Account 	= [SELECT Id,Tenuer__c,Name,
                                                   (Select Id 
                                                    From Receivables__r 
                                                    WHERE RecordTypeId =:recordTypeId)
                                                   From Financial_Account__c 
                                                   Where Opportunity__c =:opportunity_Id];
        
        AuditResponseWrapperClass auditResponse = new AuditResponseWrapperClass();
        auditResponse.auditRec 					= new API_Callout_Audit__c();
        
        if(financial_Account.Receivables__r.isEmpty()){
            try{
                auditResponse = QuickBrickAPI.sendGetRequest(financial_Account);
                createPDFFile(financial_Account.Id,taskId);
            }catch(Exception e){
                system.debug('Error::'+e.getStackTraceString());
            }
        }else{
            auditResponse.auditRec.Response__c = 'Schedule already initiated.';
            auditResponse.auditRec.API_Status__c = Label.AuditAPIStatus;
        }
        
        
        return auditResponse;
    }
    
    //@future(callout=true)
    Public static void createPDFFile(Id financial_Account_Id,Id taskId){
        WelcomeLetterController.generateWelcomeletterPDF(financial_Account_Id,taskId);
    }
    
}