force-app/main/default/objects/API_Callout_Audit__c/API_Callout_Audit__c.object-meta.xml
<CustomObject>
    <label>API Callout Audit</label>
    <nameField>
        <displayFormat>ACA-{00000}</displayFormat>
        <label>API Callout Audit</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Callout Audit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/API_Callout_Audit__c/fields/API_Status__c.field-meta.xml
<CustomField>
    <fullName>API_Status__c</fullName>
    <label>API Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Communication_Template__c/Communication_Template__c.object-meta.xml
<CustomObject>
    <label>Communication Template</label>
    <nameField>
        <displayFormat>CT-{000}</displayFormat>
        <label>Communication Template</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communication Template</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Communication_Template__c/fields/Attachment_Query__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Query__c</fullName>
    <label>Attachment Query</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Communication_Template__c/fields/CC_Addresses__c.field-meta.xml
<CustomField>
    <fullName>CC_Addresses__c</fullName>
    <label>CC Addresses</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Communication_Template__c/fields/Channel_Type__c.field-meta.xml
<CustomField>
    <fullName>Channel_Type__c</fullName>
    <label>Channel Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Communication_Template__c/fields/Email_From__c.field-meta.xml
<CustomField>
    <fullName>Email_From__c</fullName>
    <label>Email From</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Communication_Template__c/fields/Email_Service__c.field-meta.xml
<CustomField>
    <fullName>Email_Service__c</fullName>
    <label>Email Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Email_Services</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Communication_Template__c/fields/Email_To__c.field-meta.xml
<CustomField>
    <fullName>Email_To__c</fullName>
    <label>Email To</label>
    <length>75000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Communication_Template__c/fields/Template_Body_Query__c.field-meta.xml
<CustomField>
    <fullName>Template_Body_Query__c</fullName>
    <label>Template Body Query</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/EmailService.cls
public class EmailService {
    
    public static AuditResponseWrapperClass ExecuteEmailServices(Id taskId,String parentDocId){
        AuditResponseWrapperClass auditResponse = new AuditResponseWrapperClass();
        List<String> toAddresses = new List<String>();
        Task taskDetail = [SELECT Id,WhatId,Process_Path_Task_Detail__r.Communication_Template__r.Email_To__c,Process_Path_Task_Detail__r.Communication_Template__r.Email_From__c,
                           Process_Path_Task_Detail__r.Communication_Template__r.Email_Service__c,Process_Path_Task_Detail__r.Communication_Template__r.Template_Body_Query__c,
                           Process_Path_Task_Detail__r.Communication_Template__r.Channel_Type__c,Process_Path_Task_Detail__r.Communication_Template__r.Is_Active__c,
                           Process_Path_Task_Detail__r.Communication_Template__r.Subject__c,Process_Path_Task_Detail__r.Communication_Template__r.Template_Body__c,
                           Process_Path_Task_Detail__r.Communication_Template__c,Process_Path_Task_Detail__r.Communication_Template__r.Attachment_Query__c,
                           Process_Path_Deviation_Initiated_Task_Id__c,Process_Path_Task_Detail__r.Communication_Template__r.CC_Addresses__c
                           From Task 
                           WHERE Id =: taskId];
        system.debug('taskDetail::'+taskDetail);
        
        if(taskDetail.Process_Path_Task_Detail__r.Communication_Template__r.Email_Service__c != null){
            if(taskDetail.Process_Path_Task_Detail__r.Communication_Template__r.Email_Service__c == Constants.SALESFORCE){
                // Integrate Salesforce Email Service
                auditResponse = EmailHandler.SendEmailWithSalesforce(taskDetail,parentDocId);
            }else if(taskDetail.Process_Path_Task_Detail__r.Communication_Template__r.Email_Service__c == Constants.NIMBUS){
                // Integrate Nimbus API
                //auditResponse = EmailHandler.SendEmailWithNimbus();
            }
        }
        
        return auditResponse;
    }
    
    public static AuditResponseWrapperClass SendEmailFunction(List<String> toAddress,String Subject,String templateBody,String LinkedEntityId,String fromAddress,String CCAddresses){
        AuditResponseWrapperClass auditResponse = new AuditResponseWrapperClass();
        auditResponse.auditRec = new API_Callout_Audit__c();
        try {
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        OrgWideEmailAddress orgWideEmail = [SELECT Id, Address FROM OrgWideEmailAddress WHERE DisplayName =: fromAddress LIMIT 1];
        if(LinkedEntityId != ''){
            List<ContentVersion> files = getFirstFileOnOpportunity(LinkedEntityId);
            ContentVersion file = files[0];
            Messaging.EmailFileAttachment attachment = new Messaging.EmailFileAttachment();
            attachment.setFileName(file.Title+'.'+file.FileExtension);
            attachment.setBody(file.VersionData);
            mail.setFileAttachments(new Messaging.EmailFileAttachment[]{attachment});
            
        }
        
        
        mail.setToAddresses(toAddress);
        mail.setSubject(Subject);
        mail.setHTMLBody(templateBody);
        mail.setOrgWideEmailAddressId(orgWideEmail.Id);
        mail.setCcAddresses(new String[]{CCAddresses});
        
            Messaging.SendEmailResult[] results = Messaging.sendEmail(
                new Messaging.SingleEmailMessage[] { mail });
            system.debug('results::'+results);
            for (Messaging.SendEmailResult res : results) {
                system.debug('res::'+res);
                if (res.isSuccess()) {
                    System.debug('Email sent successfully');
                    auditResponse.auditRec.API_Status__c = Label.AuditAPIStatus;
                    auditResponse.auditRec.Request__c = 'Subject :' + Subject+','+'To address: ' + mail.getToAddresses() + ','+'From address: ' + mail.getReplyTo() + ',' + 'Template Body : ' + templateBody;
                    auditResponse.auditRec.Response__c = 'Email sent successfully';
                    auditResponse.auditRec.Status_Code__c = '200';
                }
                else {
                    System.debug('The following errors occurred: ' + res.getErrors());
                    for(Database.Error err : res.getErrors()) {
                        auditResponse.auditRec.API_Status__c = Label.AuditAPIFailedStatus;
                        auditResponse.auditRec.Response__c = err.getMessage();
                        auditResponse.auditRec.Status_Code__c = String.valueOf(err.getStatusCode());
                    }
                    
                }
            }
            
        } catch (Exception e) {
            System.debug(e.getMessage());
            auditResponse.auditRec.API_Status__c = Label.AuditAPIFailedStatus;
            auditResponse.auditRec.Response__c = e.getMessage();
            auditResponse.auditRec.Status_Code__c = '404';
        }
        
        return auditResponse;
    }
    
    public static List<ContentVersion> getFirstFileOnOpportunity(Id LinkedEntityId) {
        List<ContentVersion> firstFileList = new List<ContentVersion>();
        List<Id> contentDocumentIds = new List<Id>();
        for (ContentDocumentLink link : [SELECT ContentDocumentId 
                                         FROM ContentDocumentLink 
                                         WHERE LinkedEntityId = :LinkedEntityId]) {
                                             contentDocumentIds.add(link.ContentDocumentId);
                                         }
        if (!contentDocumentIds.isEmpty()) {
            firstFileList = [SELECT Id, Title, VersionNumber, ContentDocumentId,VersionData,FileExtension  
                             FROM ContentVersion 
                             WHERE ContentDocumentId IN :contentDocumentIds 
                             ORDER BY CreatedDate ASC LIMIT 1];
        }
        system.debug('firstFileList::'+firstFileList);
        return firstFileList;
    }
    
}