force-app/main/default/objects/Document_Handler__c/Document_Handler__c.object-meta.xml
<CustomObject>
    <label>Document Handler</label>
    <nameField>
        <label>Document Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Handler</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Handler__c/fields/Document_Metadata__c.field-meta.xml
<CustomField>
    <fullName>Document_Metadata__c</fullName>
    <label>Document Metadata</label>
    <referenceTo>Document_Metadata__c</referenceTo>
    <relationshipLabel>Document Handler</relationshipLabel>
    <relationshipName>Document_Handler</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Document_Handler__c/fields/Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Financial_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Account</label>
    <referenceTo>Financial_Account__c</referenceTo>
    <relationshipLabel>Document Handler</relationshipLabel>
    <relationshipName>Document_Handler</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Metadata__c/Document_Metadata__c.object-meta.xml
<CustomObject>
    <label>Process Document Metadata</label>
    <nameField>
        <label>Document Metadata Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Document Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Account__c/Financial_Account__c.object-meta.xml
<CustomObject>
    <description>To store the financial account details of Loan and Insurance</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Account__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>Financial_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receivable__c/Receivable__c.object-meta.xml
<CustomObject>
    <label>Receivable</label>
    <nameField>
        <label>Receivable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Receivables</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Receivable__c/fields/Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Financial_Account__c</fullName>
    <label>Financial Account</label>
    <referenceTo>Financial_Account__c</referenceTo>
    <relationshipLabel>Receivables</relationshipLabel>
    <relationshipName>Receivables</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Receivable__c/fields/Receivable_Date__c.field-meta.xml
<CustomField>
    <fullName>Receivable_Date__c</fullName>
    <label>Receivable Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/WelcomeLetterControllerTest.cls
@isTest
public class WelcomeLetterControllerTest {
    
    @isTest
    static void testControllerInitialization() {
        Test.startTest();
        
        // Assuming createTestAccount and CreateFinancialAccountInstance methods do not insert the accounts
        Account testAccount = TestUtility.createTestAccount();
        Financial_Account__c financialAccount = TestUtility.CreateFinancialAccountInstance();
        financialAccount.Account_Name__c = testAccount.Id;
       	Contact contactRec = TestUtility.CreateContactINstance();
        insert contactRec;
		        
        List<Receivable__c> receivables = new List<Receivable__c>();
        Receivable__c receivable = new Receivable__c(
            Financial_Account__c = financialAccount.Id,
            Receivable_Date__c = Date.today(),
            RecordTypeId = Schema.SObjectType.Receivable__c.getRecordTypeInfosByName().get('Repayment Schedule').getRecordTypeId()
        );
        receivables.add(receivable);
        insert receivables;
        
        Test.setCurrentPageReference(new PageReference('Page.WelcomeLetterTemplate'));
        ApexPages.currentPage().getParameters().put('id', financialAccount.Id);
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(financialAccount);
        WelcomeLetterController controller = new WelcomeLetterController(stdController);
        
        Test.stopTest();
        
        System.assertEquals(financialAccount.Id, WelcomeLetterController.fa_Record.Id);
        System.assertEquals(1, WelcomeLetterController.receivableList.size());
        System.assertEquals(receivable.Id, WelcomeLetterController.receivableList[0].Id);
    }
    @isTest
    static void testGenerateWelcomeLetterPDF() {
        Test.startTest();
        
        Account testAccount = TestUtility.createTestAccount();
        Financial_Account__c financialAccount = TestUtility.CreateFinancialAccountInstance();
        financialAccount.Account_Name__c = testAccount.Id;
        //insert testAccount;
        //insert financialAccount;
        
        Receivable__c receivable = new Receivable__c(
            Financial_Account__c = financialAccount.Id,
            Receivable_Date__c = Date.today(),
            RecordTypeId = Schema.SObjectType.Receivable__c.getRecordTypeInfosByName().get('Repayment Schedule').getRecordTypeId()
        );
        insert receivable;
        
        Task task = new Task(WhatId = testAccount.Id);
        insert task;

        Document_Metadata__c docMetaRec = TestUtility.createDocumentmetadata(); 
       
        
        
        

        
        String result = WelcomeLetterController.generateWelcomeletterPDF(financialAccount.Id, task.Id);
        
        Test.stopTest();
        
        List<Document_Handler__c> handlers = [SELECT Id FROM Document_Handler__c WHERE Financial_Account__c = :financialAccount.Id];
        System.assertEquals(0, handlers.size());
    }
    
    
}