force-app/main/default/objects/Document_Handler__c/Document_Handler__c.object-meta.xml
<CustomObject>
    <label>Document Handler</label>
    <nameField>
        <label>Document Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Handler</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Handler__c/fields/Document_Metadata__c.field-meta.xml
<CustomField>
    <fullName>Document_Metadata__c</fullName>
    <label>Document Metadata</label>
    <referenceTo>Document_Metadata__c</referenceTo>
    <relationshipLabel>Document Handler</relationshipLabel>
    <relationshipName>Document_Handler</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Document_Handler__c/fields/Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Financial_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Account</label>
    <referenceTo>Financial_Account__c</referenceTo>
    <relationshipLabel>Document Handler</relationshipLabel>
    <relationshipName>Document_Handler</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Handler__c/fields/Task_Id__c.field-meta.xml
<CustomField>
    <fullName>Task_Id__c</fullName>
    <label>Task Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Metadata__c/Document_Metadata__c.object-meta.xml
<CustomObject>
    <label>Process Document Metadata</label>
    <nameField>
        <label>Document Metadata Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Document Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Account__c/Financial_Account__c.object-meta.xml
<CustomObject>
    <description>To store the financial account details of Loan and Insurance</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Account__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>Financial_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Loan Amount Applied</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/EMI_Amount__c.field-meta.xml
<CustomField>
    <fullName>EMI_Amount__c</fullName>
    <label>EMI Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/LOS_Application_ID__c.field-meta.xml
<CustomField>
    <fullName>LOS_Application_ID__c</fullName>
    <label>LOS Application ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/Sanction_Date__c.field-meta.xml
<CustomField>
    <fullName>Sanction_Date__c</fullName>
    <label>Sanction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/Sanctioned_Amount__c.field-meta.xml
<CustomField>
    <fullName>Sanctioned_Amount__c</fullName>
    <label>Sanctioned Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Financial_Account__c/fields/Tenuer__c.field-meta.xml
<CustomField>
    <fullName>Tenuer__c</fullName>
    <label>Tenuer</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Receivable__c/Receivable__c.object-meta.xml
<CustomObject>
    <label>Receivable</label>
    <nameField>
        <label>Receivable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Receivables</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Receivable__c/fields/Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Financial_Account__c</fullName>
    <label>Financial Account</label>
    <referenceTo>Financial_Account__c</referenceTo>
    <relationshipLabel>Receivables</relationshipLabel>
    <relationshipName>Receivables</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Receivable__c/fields/Intrest_Amount__c.field-meta.xml
<CustomField>
    <fullName>Intrest_Amount__c</fullName>
    <label>Intrest Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Receivable__c/fields/Principal_Amount__c.field-meta.xml
<CustomField>
    <fullName>Principal_Amount__c</fullName>
    <label>Principal Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Receivable__c/fields/Principal_Outstanding__c.field-meta.xml
<CustomField>
    <fullName>Principal_Outstanding__c</fullName>
    <label>Principal Outstanding</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Receivable__c/fields/Receivable_Date__c.field-meta.xml
<CustomField>
    <fullName>Receivable_Date__c</fullName>
    <label>Receivable Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Receivable__c/fields/Series__c.field-meta.xml
<CustomField>
    <fullName>Series__c</fullName>
    <label>Series</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WelcomeLetterController.cls
public class WelcomeLetterController {
    public static Financial_Account__c fa_Record{get;set;}
    public static List<Receivable__c> receivableList{get;set;}
    public static date installment_date{get;set;}
    public static Contact contact_details{get;set;}
    public WelcomeLetterController(ApexPages.StandardController ctrl){
        // if(ctrl.getId()!=null){
        // system.debug('ID === >'+ctrl.getId());
        system.debug('ctrl::'+ctrl);
        system.debug('ctrl.getId()::'+ctrl.getId());
        system.debug('inside the construction');
        Id financialAccountId = ctrl.getId();
        
        getFinancialDetails(financialAccountId);
        //}
    }
    
    public static void getFinancialDetails(Id financialAccountId){
        system.debug('financialAccountId::'+financialAccountId);
        fa_Record = [SELECT Id,Name,Sanctioned_Amount__c,Account_Name__r.Phone,
                     Sanction_Date__c,Tenuer__c,EMI_Amount__c,Account_Name__c,LOS_Application_ID__c
                     From Financial_Account__c 
                     Where Id =: financialAccountId];
        Id recordTypeId = Schema.SObjectType.Receivable__c.getRecordTypeInfosByName().get('Repayment Schedule').getRecordTypeId();
        receivableList = [SELECT Id,Series__c,Intrest_Amount__c,Amount__c,
                          Receivable_Date__c,Principal_Amount__c,Principal_Outstanding__c 
                          From Receivable__c 
                          WHERE Financial_Account__c =: financialAccountId 
                          and RecordTypeId =: recordTypeId];
        
        contact_details = [SELECT Id,MailingStreet,MailingCity,
                           MailingState,MailingPostalCode,MailingCountry,Name
                           From Contact 
                           where accountId =: fa_Record.Account_Name__c];
        installment_date = receivableList.size()>0 ?receivableList[0].Receivable_Date__c:null;
    }
    
    @AuraEnabled
    public static string generateWelcomeletterPDF(String recordId,String taskId){
        system.debug('recordId == >'+recordId);
        List<Attachment> attachList = new List<Attachment>();
        blob pdfBody;
        try{
            
            List<Receivable__c> ReceivableRecList = new List<Receivable__c>();
            Id recordTypeId = Schema.SObjectType.Receivable__c.getRecordTypeInfosByName().get('Repayment Schedule').getRecordTypeId();
            ReceivableRecList = [SELECT Id From Receivable__c 
                                 WHERE Financial_Account__c =: recordId and RecordTypeId =: recordTypeId];
            
            Document_Metadata__c docMetaRec = [select id,Document_Name__c from Document_Metadata__c where Document_Name__c='Welcome Letter' limit 1];
            
            Id DocumentHandlerId = [Select Id From Document_Handler__C where Document_Metadata__C =: docMetaRec.Id and Task_Id__C =:taskId].Id;
            
            PageReference pdfPage = Page.WelcomeLetterTemplate;
            pdfPage.getParameters().put('id',recordId);
            pdfBody = (!Test.isRunningTest() ? pdfPage.getContent() : Blob.valueOf('For Test Class'));
            
            lwc_Handledocuments_Controller.uploadFile(EncodingUtil.base64Encode(pdfPage.getContentAsPDF()),'Welcome Letter.pdf',DocumentHandlerId,taskId);
            
        }catch(Exception e){
            system.debug('Error == >'+e.getMessage()+'  && Error line == >'+e.getLineNumber());
        }
        return null;
    }
}